### ISSUE TITLE
syntax-checking mode

### ISSUE THREAD

**Issue by VladimirAlexiev** [sparql-generate/sparql-generate#100]
I want to use sparql-generate to check the syntax of my query while I'm editing it.
I know about https://ci.mines-stetienne.fr/sparql-generate/playground.html and https://sparql-generate.github.io/sparql-generate-editor/ but I prefer a desktop editor.

Eg https://github.com/ljos/sparql-mode/issues/29 shows how to use jena `query` for emacs `flycheck`.

If the query has an error, sparql-generate prints something like this:
```
07:07,723 main ERROR fr.mines_stetienne.ci.sparql_generate.lang.ParserSPARQLExt:155 -
org.apache.jena.query.QueryParseException: Lexical error at line 10, column 8.  Encountered: " " (32), after : "zselect"
        at fr.mines_stetienne.ci.sparql_generate.lang.ParserSPARQLExt.perform(ParserSPARQLExt.java:154)
        at fr.mines_stetienne.ci.sparql_generate.lang.ParserSPARQLExt.parse$(ParserSPARQLExt.java:79)
```

Could you add an option `--syntax` to print only the error line:
```
Lexical error at line 10, column 8.  Encountered: " " (32), after : "zselect"
```
- And of course, not to execute the query even if it's valid
- If it's possible to print all errors instead of just one, that would be super!

**Comment by maximelefrancois86** [comment]
Hi, this feature will be shipped in the next release.

Are you aware of the sublime text package ? https://ci.mines-stetienne.fr/sparql-generate/sublime.html 

![image](https://user-images.githubusercontent.com/11416248/114843797-7b2e5f00-9dda-11eb-85a2-ad06d7d96004.png)
