### ISSUE TITLE
Throw error when URL Request fails

### ISSUE THREAD

**Issue by smierz** [sparql-generate/sparql-generate#101]
Hello,

I'm using the library to query an API via a HTTP Get Request using the Locator for URLs and it is working nicely except when the HTTP Get Request fails (http.getResponseCode !=200) the execution just continues and the output is of course an empty Model.

Could you please throw an error in that case instead of continuing on?

**Comment by maximelefrancois86** [comment]
Hello,

With new binding function [fun:HTTPGet](http://w3id.org/sparql-generate/fn/HTTPGet) you can operate a HTTP Get operation, retrieve the full HTTP response, then check the response code is 200 with [fun:HTTPExtractResponseCode](http://w3id.org/sparql-generate/fn/HTTPExtractResponseCode)

**Comment by smierz** [comment]
Thank you. 
While I can extract the Response Code, I can not distinguish the situations, where the Request fails and where the response is empty. Both continue computing and result in an empty jena model.
However this helps me in throwing an error when the request failed  like this

`BIND(IF(fun:HTTPExtractResponseCode =200, 1, 1/0) AS ?throwerror)`
