### ISSUE TITLE
Support HTTP Post requests

### ISSUE THREAD

**Issue by smierz** [sparql-generate/sparql-generate#102]
Hello, it would be nice to be able to use http post requests as a input source as well, for querying APIs.

If the library could read data from different APIs it would broaden the focus from a transformation tool to a complete Data Ingest Pipeline.

**Comment by maximelefrancois86** [comment]
Hello, 

New binding function [fun:HTTPPost](http://w3id.org/sparql-generate/fn/HTTPPost) operates a HTTP Post operation.
- Param 1: (a URL) the IRI of the target resource;
- Param 2: (string): additional HTTP headers for the request.
- Param 3: (string): body of the request.

It returns the full HTTP response as a literal. You can:

- extract and check response code with http://w3id.org/sparql-generate/fn/HTTPExtractResponseCode
- extract header with http://w3id.org/sparql-generate/fn/HTTPExtractHeader
- extract body with http://w3id.org/sparql-generate/fn/HTTPExtractBody

**Comment by smierz** [comment]
Thanks a lot, this is a very helpful extension.

Could you give an example with context?
I assumed it would be something like the line below but I get an exception:

`SOURCE fun:HTTPPost("https://api.datacite.org/graphql",  , "{organization(id:\\"https://ror.org/04aj4c181\\"){name}}") AS ?graphqlapi`

**Comment by maximelefrancois86** [comment]
Hi, 

`fun:HTTPPost` should not be used inside `SOURCE`.

Instead, use it as a binding function: anywhere where an expression can be used.

If you do not have a header, use unbound variable `?undef` or empty string `""` instead. 

Here is a minimal working example. 
[See it live](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgA6AOwAKAJTIAxAJIANCgEskmXNTqMWzAO4BmTWH7CMAc2YBnBjAwoEAWhsRpmGDubbMCRkFZXUKKDhpPVp6JlYzCytbBycXd09vDF8IZihpILlFVQ12ezBogziTY2N+MyS7ACYABmaARmY1AFkAGRJBGgguGABiKULQjQ4K2KMObl4BaztxmXIesgBhABUKAH5pbggZGQB1AAkyRQpgGQoKAhUAOQARAAp7iKjz7e3ZWWE9iQbxijHsRhgDE0-DAvhgggCDWYNiyDBornEABoKJIQJthNIdIS3EgsAwIHpIbxNIJfJoCcwAFb2Am4ijY3GckCSSS3EDCclZJD06RPI643DSRAITG4gBuzk0MAARnx7BKecAAL6ykBoTBYDXc3nLGDSTQALzpBLeFj0PIdIEq4NYGGsSOaABYYIzPYI2gAONoOnkgACUON5hy4EC1Wtx8e5SYjpH2GAgjgJ9ggFDDdwoqh62yuHy+uB+fzI7CQWUESHkGYYWYg+MgHz26cz0mzuYoAF4KC1mrn849XqXIuXfrIqzX4UgCMIwFh252m92cymSPtlUusCPpPcx+9wpOAFIkADyT1kvho7d3y45IAAJDC4Q0zZbrdJ+NHjiAvapgcRwHvcMjxtIICYiA-5gPqGCaBmeAANoALowZAsCIEgKKQjQeAgNBsFHGAeFovYqEYeAwiCHAMaEtmSBUTBQLptweCwAg2YwQgwg2HwcoQAgeAAKxakAA)


```
BASE <http://example.com/>
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
SELECT ?name
WHERE {
  BIND(  fun:HTTPPost(<https://api.datacite.org/graphql>, "Content-type: application/json" , """\{"operationName":null,"variables":\{},"query":"\{organization(id: \\"https://ror.org/04aj4c181\\") \{name}}"}""") AS ?response )
  FILTER( fun:HTTPExtractResponseCode( ?response ) = 200 )
  BIND( fun:HTTPExtractBody( ?response ) AS ?body )
  BIND( fun:JSONPath( ?body, "$.data.organization.name" ) AS ?name ) 
}
```
