### ISSUE TITLE
How to bind XML node name?

### ISSUE THREAD

**Issue by alexdma** [sparql-generate/sparql-generate#105]
Given an XML file which, in a minimal example, looks like this:
```
<root>
  <obj>
    <a5000>08155906</a5000>
  </obj>
  <obj>
    <a5001>08030751</a5001>
  </obj>
</root>
```
I would like to generate the following triples:
```
@prefix ex: <http://example.com/> .
<http://example.com/object/08155906>  ex:hasID  <http://example.com/id/a5000/08155906> .
<http://example.com/object/08030751>  ex:hasID  <http://example.com/id/a5001/08030751> .
```
To do so, I need to:
1. grab the value for a tag that may be either `a5000` or `a5001` (they are mutually exclusive in each `obj`)
2. grab the name of the tag

I think I have found how to accomplish (1), but the way I would use XPath to accomplish (2) does not seem to bear results:

```
GENERATE { 
    <http://example.com/object/{?id}>  ex:hasID  <http://example.com/id/{?idtype}/{?id}> .
}
SOURCE <http://example.com/document.xml> AS ?source
ITERATOR ite:XPath(?source, "//obj" ) AS ?obj
WHERE {
     BIND( fun:XPath(?obj, "(/obj/a5000 | /obj/a5001)/text()"  ) AS ?id )
     BIND( fun:XPath(?obj, "(/obj/a5000 | /obj/a5001)/name()"  ) AS ?idtype )
} 
```
Variable `id` is bound, but trying `idtype` has resulted in the following
```
main WARN  fr.mines_stetienne.ci.sparql_generate.xml.FUN_XPath:135 - The XPath expression is not valid: (/obj/a5000 | /obj/a5001)/name() - exception is javax.xml.transform.TransformerException: Unknown nodetype: name

```
I have also tried the XPath 1 version `"name(/obj/a5000 | /obj/a5001)"` obtaining the following:
```
main WARN  fr.mines_stetienne.ci.sparql_generate.xml.FUN_XPath:135 - The XPath expression is not valid: name((/obj/a5000 | /obj/a5001)) - exception is com.sun.org.apache.xpath.internal.XPathException: Can not convert #STRING to a NodeList!
```
I have been referring to the function specification at https://www.w3.org/2005/xpath-functions/

What is the correct way to bind the name of an XML element?

Thanks

**Comment by maximelefrancois86** [comment]
the `sparql-generate-xml` module relies on the standard `javax.xml.xpath` package, which is meant ot conform to XPath1

see https://docs.oracle.com/javase/7/docs/api/javax/xml/xpath/package-summary.html

I can propose the following query as an alternative, would if work for your general use case?


```
BASE <http://example.com/> 
PREFIX ite: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX ex: <http://example.com/>
GENERATE { 
    <http://example.com/object/{?id}>  ex:hasID  <http://example.com/id/{?idtype}/{?id}> .
}
SOURCE <http://example.com/document.xml> AS ?source
ITERATOR ite:XPath(?source, "//obj" ) AS ?obj
WHERE {
  VALUES ?idtype { "a5000" "a5001" }  
  BIND( fun:XPath(?obj, "/obj/{ ?idtype }/text()"  ) AS ?id )
} 
```

[see working example](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSCLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNDhjDeLZOHj4hUUKAcTIAOTIFIgAVSmBpGV6KAYM44w5uXgERMWEAIwArCEEkZmAAfksAX0kKMpoYB1UAEQHYo1ZRmon6y2W1sCQsBgh1m43JfllZddkSAHkAVQUAGFKCdKudxnUxGBhII4FxvEh+OwuAhJKQKCsHMI4BhBBBZKouu0Oj8FNpdLh1HI-DQABSY7G4iAAGmkIFYM1mUhAFAAlBR0StObIAOoACTa3VkAwAakQADJ-MgkDGWe6PCg9bkwACsAAYDdy2bqDQBGI3rAbSigEVTNA60iJRSnUpB0oVzVnc5ic5aqu4PCAUZ66dhIWm8o18gUq258z4UEDMkAybgQMBoTBaCAOPAAbQAusnILBEEhbNkGDQ8CAkym02AKzAq7ncIXizC4QiHBAkPnQDitDWKiNqhDJsxobD4TJEciEHWHEgMFoZLYa1QVvOKAA3TAOLTCGQAXm5pv4eqN3hEYFXtlPID+HWU7gAHNyVuJZFQMMJhEgvz6ahOUAwZqBNA1xD1V9TR1HUAE49QANioZgIL1UDqB9OZMKoEDrWOCDTSg189TMPUAHYdVNVCiNw7DZkA1Df3-cQ63hW8-EDGtm14LRBD8Q8CnnEB1iLEAlwwCBuDwWAEB7ZMEGEWw+D3BdcB1dYgA)

**Comment by alexdma** [comment]
Thanks @maximelefrancois86 ! I suppose that if the XML file gets more complex (like in #106 ), the VALUES clause will need to be repeated, but as a stop-gap solution to stay in XPath1 this will work.
