### ISSUE TITLE
expose StreamRDF for postprocessing

### ISSUE THREAD

**Issue by smierz** [sparql-generate/sparql-generate#111]
Hello Maxime,
I was wondering if it would make sense to expose the StreamRDF that is used in the execution (see RootPlan.java), like 
`public StreamRDF execGenerateStream(QuerySolution initialBindings, Context context);`

The use case I'm thinking of is to write the generated triples to a triple store instead of a file and this could be done with a StreamRDF as described here https://jena.apache.org/documentation/rdfconnection/  (bottom of the website under point "Examples"):

> for example of how to use with StreamRDF see https://github.com/apache/jena/blob/main/jena-examples/src/main/java/org/apache/jena/example/streaming/StreamRDFToConnection.java.

**Comment by maximelefrancois86** [comment]
When using `StreamRDF`, usually you implement this interface, then pass an instance of your implementation as a parameter to one of the `execGenerate` methods. This is what I use for example in https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-jena/src/main/java/fr/mines_stetienne/ci/sparql_generate/cli/ConsoleStreamRDF.java  or https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-jena/src/main/java/fr/mines_stetienne/ci/sparql_generate/cli/HDTStreamRDF.java
