### ISSUE TITLE
Exception is not thrown

### ISSUE THREAD

**Issue by aliariff** [sparql-generate/sparql-generate#129]
Why in these line 
https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-jena/src/main/java/fr/mines_stetienne/ci/sparql_generate/engine/IteratorPlan.java#L127-L133
the exception is silenced?

Is there any particular reason for it? How to get the exception?

**Comment by maximelefrancois86** [comment]
There is some logging, so we can't say the exception is silenced.

This is the desired behaviour: if the iterator fails to process one binding, it should not make the whole transformation fail.

**Comment by aliariff** [comment]
Hi @maximelefrancois86 

Thank you for your response. I understand that, but for us we want it to fail and throw an exception.
May I suggest solution here, that we add a new context key so that the caller can enable whether they want the transformation throw exception or not. What do you think?

**Comment by maximelefrancois86** [comment]
ok. I'd like to know more about your rationale

**Comment by aliariff** [comment]
So we use sparql-generate as a library to our project, we run the transformation programatically following this example here https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-example/src/main/java/fr/mines_stetienne/ci/sparql_generate/example/Main.java

and currently we need to tell whether there is an error while performing the transformation, hence we need the exception to be thrown to the caller so that we can do something with it (like change the state of our business logic, get the detail error message instead of reading it from console terminal log, etc).

While the log message is indeed enough for user that use the CLI tool, it is not the case for user that use this as external library.

**Comment by maximelefrancois86** [comment]
ok thanks for the details

**Comment by aliariff** [comment]
What do you think about my suggestion to add a new context key for deciding to throw exception or not to throw?
Or maybe you have suggestion on how to get the exception with current codebase?

**Comment by maximelefrancois86** [comment]
Yes, I'm ok with the proposal to introduce a context key for deciding when to throw an exception. 
Please let the default behaviour be the current behaviour, so that users do not notice a big difference
