### ISSUE TITLE
Inconsistent exception handling

### ISSUE THREAD

**Issue by aliariff** [sparql-generate/sparql-generate#130]
In some iterator an exception is not rethrown like in here:

https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-csv/src/main/java/fr/mines_stetienne/ci/sparql_generate/csv/ITER_CSV.java#L144-L148

And in other location it is rethrown, like in here:

https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-json/src/main/java/fr/mines_stetienne/ci/sparql_generate/json/ITER_JSONSurfer.java#L136-L150

Furthermore the rethrown part is not passing the cause exception, like in here:
- https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-json/src/main/java/fr/mines_stetienne/ci/sparql_generate/json/ITER_JSONSurfer.java#L141
- https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-json/src/main/java/fr/mines_stetienne/ci/sparql_generate/json/ITER_JSONSurfer.java#L149
- https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-json/src/main/java/fr/mines_stetienne/ci/sparql_generate/json/ITER_JSONPath.java#L207

**Comment by maximelefrancois86** [comment]
PR accepted.
