### ISSUE TITLE
Examples on Playground not available anymore

### ISSUE THREAD

**Issue by jmkeil** [sparql-generate/sparql-generate#132]
Hi, it looks like the examples on the [playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html) are not available anymore due to an 503 error.

**Comment by maximelefrancois86** [comment]
Thank for the notification.
`sparql-generate-server` is now compiled with Java 11, and the Jetty docker image used on the server was using Java 8.
I migrated to `jetty:9.4-jdk11`
Let me know if you find any issue

**Comment by jmkeil** [comment]
Thanks a lot for the fast fix.
