### ISSUE TITLE
Support stream via sockets

### ISSUE THREAD

**Issue by pheyvaer** [sparql-generate/sparql-generate#14]
Hi,

Is it possible to map data that is coming from a socket? I saw the `stream` folder in the code, but it looks like that is for streaming static files from disk.

**Comment by maximelefrancois86** [comment]
Hi,

The `stream` package is there to complement the `stream` package from jena.

What you would require for your use case is to create creating a new "Iterator" class in the `iterator.library` package. What is your use case ? what kind of socket and what kind of format ? 

You can have a look at `CSVStream` iterator that processes (big) CSV documents and iterates over the lines, a few lines at a time.  That could be adapted to connect to a stream source, and iterate over some bytes/lines, a few at a time, using a buffer.

Technically speaking, SPARQL-Generate is no stream-based RDF generator, more like batch-based

**Comment by ysedira** [comment]
Hi,

I am doing something similar to what Pieter described earlier, which is receiving JSON messages from a stream and I want to map them to RDF.
More specifically, what I am trying to do is something like this: 
On message reception, save the message in a file, then customise a SPARQL-Generate query that uses this file as a source and maps its content to RDF. 
I tried referencing a local file but it didn't work, so my question is is that even possible? or does it have to be an HTTP URI?

Another approach that I am looking into it is to use a `SPARQL 1.1 Value clause` and omit the `Source clause`, 
I saw bnode1 test in the playground section, but I am not sure how to use it with JSON or XML values, any ideas?

Thank you,

**Comment by maximelefrancois86** [comment]
Dear Yehia, 

Maybe a little loop could be of help here? 
This use case has been dealt with before and a solution is documented here

https://ci.mines-stetienne.fr/sparql-generate/get-started.html#Generating_RDF_for_streams_of_messages

No need to save messages in files (this would slow down the transformation). On the other hand, it should actually work to use the file URI scheme in the SOURCE clause to load a local file...

Best,
Maxime
