### ISSUE TITLE
Aggregates in SPARQL-Generate

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [sparql-generate/sparql-generate#15]
Assume I have the following data in CSV:

    id,location,temp
    sensor1,room1,13.0
    sensor2,room1,10.5
    sensor3,room1,14.9
    sensor4,room2,9.1
    sensor5,room2,9.5
    
generate :

    <room1>  a  ont:Room;
        ont:temp   12.8 .
    <room2>  a  ont:Room;
        ont:temp   9.3 .

which requires the computation of an average for groups of values in the same room.
Currently, aggregates cannot be used in SPARQL-Generate because they can only appear in a SELECT clause, which is not allowed for now. A solution could be to allow sub-SELECT in the WHERE clause:

    GENERATE {
       <{?room}>  a  ont:Room;
          ont:temp  ?avgTemp .
    }
    SOURCE <...> AS ?source
    ITERATE iter:CSV(?source) AS ?line
    WHERE {
       BIND(fn:CSV(?line,"room") AS ?room)
       SELECT (AVG(?temp) AS ?avgTemp) WHERE {
           BIND(fn:CSV(?line,"temp") AS ?temp)
       } 
       GROUP BY ?room
    }

**Comment by maximelefrancois86** [comment]
Now implemented  :-)

See it [live on the playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#ex=example/generate/04-Aggregators)

**Comment by maximelefrancois86** [comment]
Here is a [live example of your example on the playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEA9gHZK40A8AFkkgA64D0fCAA8YAW24IIAOjoYA5n0ZIAxAD4AOg2LlqNAJZIILDl14CA7gGY9YGfL4BnbjAwoEAWjkQGmGIb4GmHwaWqSUtEIOYMacPPx85olSVnYKAEwADBkAjHxUALIAMgDKAMbsEKIwapqaAOIkAHIkRACCACokNMCaNH2swAD8CHSlfnqMAL6qfTB9SrhEdHSiANy9ffRMuIbifYPANK0AanUAFOogQ7vcNJOXAHoPkdGQpXpVCACUdzRSmvcGMUAPIAVSIAGEuiY4gJhGIJNJZAowKM4KJvCoMjNWsUaIMHHQ4BhShBNBROm12sCiPpDLgIcVjmcCUSSRAfrj8TZ8SMxkgJgx8Td6kQwQQaAAhACavNG40YmhAABoQAwxBAwGhMHoIA48ABtAC6qsgsEQSDkGBg3HYeBAKrVGrAVpt7H1uGNprRGKYDggSENoGJentsTMghE4kkqT4qNK6MxygyjoxYD0fiw3Ag9sMQiQfAkMD0DEdDiQGBLcntNmVfIVDGVIoY-pbsmyyowy1EHeylikGU0rcJGDSne7vYyUgArEPvCPLOOVr2ACxSACcc7bGBXS9EY-XUmyW5H073B5nIEmJpA5YwEDEeFgCH9qpGckkADcIAg8NPJkAA)
