### ISSUE TITLE
Linked EBNF

### ISSUE THREAD

**Issue by kjetilk** [sparql-generate/sparql-generate#18]
Hi! 

Great work! 

I just wanted to say that for SPARQL-Generate implementors, I think it would helpful if you could put the grammar of EBNF that you have in a paper on your website, linked to the corresponding parts of the SPARQL 1.1 spec.

Cheers,

Kjetil

**Comment by maximelefrancois86** [comment]
Hi, the syntax can be found in the javacc .jj file, it has evolved since the paper (addition of syntactic sugar). I'll assign this to our new research engineer @infomehdi
