### ISSUE TITLE
Please add Docker support.

### ISSUE THREAD

**Issue by amalic** [sparql-generate/sparql-generate#19]
I can try to do this if you want?

**Comment by maximelefrancois86** [comment]
Can you catch me at the conference tomorrow to talk about it ? Do you mean: add docker support for https://github.com/sparql-generate/sparql-generate-ws ? (SPARQL-Generate server with websocket)

**Comment by amalic** [comment]
which conference?

**Comment by maximelefrancois86** [comment]
Oups, ESWC18, we presented a tutorial on SPARQ-Generate yesterday, I thought your comment was a positive reaction to this event.

**Comment by maximelefrancois86** [comment]
Hi, 
We would be glad to have your help here to design a dockerimage. 
Best,

**Comment by maximelefrancois86** [comment]
This issue is stale. please reopen if necessary.
