### ISSUE TITLE
Iterator JSONElement crashes

### ISSUE THREAD

**Issue by miguel76** [sparql-generate/sparql-generate#26]
If there is a dollar sign (`$`) character in the enumerated JSON structure, the iterator JSONElement crashes.

That is due to [the usage of the method `String.replaceAll()` in class `ITER_JSONElement`](https://github.com/sparql-generate/sparql-generate/blob/master/sparql-generate-jena/src/main/java/com/github/thesmartenergy/sparql/generate/jena/iterator/library/ITER_JSONElement.java#L129).
As stated in the [documentation of `String.replaceAll()`](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll(java.lang.String,%20java.lang.String)), backslashes (`\`) and dollar signs (`$`) in the replacement string have special meaning.
To solve the bug, the string to be replaced (`jsonstring`) should be first normalized by calling the method`Matcher.quoteReplacement(java.lang.String)`.
As another option, the structure could be built without using string replacement (e.g., directly through string concatenation).

**Comment by maximelefrancois86** [comment]
Dear Miguel,
Thank you for reporting this, would you maybe be willing to submit a PR that fixes this?

**Comment by miguel76** [comment]
Sure, I will try to do it
