### ISSUE TITLE
Iterator regexgroups

### ISSUE THREAD

**Issue by maximelefrancois86** [sparql-generate/sparql-generate#33]
Hi,

href does not correspond to the name of the class 

https://github.com/sparql-generate/sparql-generate/blob/b6022d03c97f45d378b4e2d94e15e2df090af5fe/sparql-generate-jena/src/main/java/com/github/thesmartenergy/sparql/generate/jena/iterator/library/ITER_regexgroups.java#L35

could you please add an example after this line?

https://github.com/sparql-generate/sparql-generate/blob/b6022d03c97f45d378b4e2d94e15e2df090af5fe/sparql-generate-jena/src/main/java/com/github/thesmartenergy/sparql/generate/jena/iterator/library/ITER_regexgroups.java#L42

**Comment by infomehdi** [comment]
Thank you for your note.
Example added.
