### ISSUE TITLE
Building URI from prefix and variable

### ISSUE THREAD

**Issue by lolive** [sparql-generate/sparql-generate#42]
I have such a query, with a prefix and a variable.

    PREFIX food: <http://world-fr.openfoodfacts.org/>
    BASE <bla>
    
    GENERATE {
    <food:{?id}> a :Item .    
    }
    SOURCE whatever...
    ITERATOR whatever...
    WHERE {
    BIND (whatever... as ?id)
    }

Currently, SparqlGenerate build subject URIs like this: take the base prefix, appends the 'food:' string, then appends the ?id value.

I would like SparqlGenerate to build the the subject URIs like that: expand the prefix food: and then appends the ?id value

Is there a compact syntax that would do just that?

**Comment by maximelefrancois86** [comment]
Hi,

There is something wrong here, I'll have to find some time to have a look at it. Please do not close the issue.

In the meantime, this is how you can generate the IRI properly:

```
PREFIX food: <http://world-fr.openfoodfacts.org/>
BASE ......

GENERATE {
<http://world-fr.openfoodfacts.org/{?id}> a :Item .
}
SOURCE whatever...
ITERATOR whatever...
WHERE {
BIND (whatever... as ?id)
}
```

**Comment by maximelefrancois86** [comment]
Back to this issue, 

The way the implementation is processing your query is totally normal. From what you describe it seems like you would want to write: `food:{?id}` (prefixed URI) and not `<food:{?id}>` (URI relative to the base) . Unfortunately we do not provide this syntactic sugar in prefixed URIs, and this is not planned.
