### ISSUE TITLE
Binding all CSV cells of a row in one line.

### ISSUE THREAD

**Issue by lolive** [sparql-generate/sparql-generate#43]
When iterating a CSV, is there a function (usable in the WHERE clause) to bind each cell value to a variable named after the column name?

**Comment by infomehdi** [comment]
I think `CSVMultipleOutput` if what you are looking for.
Please load example _07-MultipleOutputsIterator_ in the [Playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html) to show a demonstration of how does it work.

**Comment by lolive** [comment]
Can I use the catch-all "*" to capture all column names at once?

**Comment by infomehdi** [comment]
> Can I use the catch-all "*" to capture all column names at once?

"*" is not supported yet in the `CSVMultipleOutput` iterator. 
We already support in for the `CSVStream` iterator, we can add it to `CSVMultipleOutput` in the very next pull request.

Untill then, please provide all the column names:
to iterator over the rows of such a csv file

```
col_X,col_Y,col_Z
val_X1,val_Y1,val_Z1
val_X2,val_Y2,val_Z2
```

`ITERATOR ite:CSVMultipleOutput(?source, ",", "col_X","col_Y","col_Z") AS ?x ?y ?z`

**Comment by lolive** [comment]
May be you should tag that issue as <Enhancement>

**Comment by maximelefrancois86** [comment]
@infomehdi  could you please update the PR #46, there is currently a conflict and this PR cannot be merged.

**Comment by maximelefrancois86** [comment]
To answer your initial question: I don't think it would be wise to automatically bind variables to the column names. Some reasons are:

- column names may not be valid variable names 
- there may be no header
- the query would have different semantics depending on the document that is fetched

At least you can select *all* columns with [`iter:CSV`](http://w3id.org/sparql-generate/iter/CSV):

See it in [live on the playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCOSrjjDm5eARExcVlZcl6yAGEAFQoAKllVXbIFIl2AeQVtXQxcbZIANQAKWKNWBZ4+IVFmERkDjgPCQWmEMiEDgAbuIAJQUUgUAD8YByuy0XAgJCQGGRDiQNggyO4wiiSGRAKBmIwsgA6gAJM6UYAUAC+IAANCAZNwIGA0JgtBAHHgANoAXS5kFgiCQtmyDBoeBAnO5vLA8pgipFuAlUuEgmB3iQDggSDFoDgGC0yqq80432Wf0pwIYoPBkKhqvx1pktmVqN0HPxhI5JLJHJd1NkrXaAE53C0AKyJ9q7Nq4JMtXAtBMtADsOZaHLjSY5ZiTTX4ZjMHIUMAAVjAYx08ymOrsmmZM00cwA2ROFtocvtx8tJgAs-FLHN2WAw4IgLfjifbTXT2azuDME8HRY5AA4J+OD-w+-mOfTMAuwMu24mzOn2kXcBPdwX9-ni2Ymknq2WACkYEEABrBxwTvVcH3TJNcHaQt4L3YcJ2-CcqxaWs5BgGQwBsZsZFje8MN2dpYJQuD3yHYsDzLMw+xafh4I5MgoQgVVnCQJV8Fww1MRkE0zX+cEqTdMEIUEaFVUxMAtD8LAGDY-BdHYJB-kk1lJRAH0IG4PAcXQLkEGEWw+FYhA8CTVkgA)
