### ISSUE TITLE
Setting the separator in CSVStream

### ISSUE THREAD

**Issue by lolive** [sparql-generate/sparql-generate#44]
How to set the CSV separator with iter:CSVStream?

**Comment by infomehdi** [comment]
The separator is set, by default, to ","

**Comment by lolive** [comment]
Too bad when the input file is a TSV.

**Comment by maximelefrancois86** [comment]
With the lastest version and iterator [`iter:CSV`](http://w3id.org/sparql-generate/iter/CSV) you can now do this.

See this [in action on the playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCOSrjjDm5eARExcVlZcl6yAGEAFQoAKllVXbIFIl2AeQVtXQxcbZIANQAKWKNWBZ4+IVFmERkDjgPCQWmEMiEDgAbuIADQUJAYdDwqQgKTotEgFEgADcqOx6Jk+IoZgAlBRSBQAPxgHK7LRcCAkRHUhxIGwQancYRRJDUgFAxkYWQAdQAEmdKMAKABfLEgGTcCBgNCYLQQBx4ADaAF1YeBoPBkLZsgwaHgQPLFYywCaYGbNbhdfqwMJBMDvEgHBAkNrQHAMFoLVV5pxvss-gLgQxQeDIVD5WzAzJbBbabocWyOTjubycVGhbJWu0AJzuFoAVnL7V2bVwFZauBaZZaAHYmy0cSWKzizBWmvwzGYcQoYAArGBFjotqsdXZNMz1ppNgBs5fbbRxK5LvYrABZ+N2cbssBhwRAp6Xy7OmrXGw3cGY9+uOziABx73dv-gr1s4sWYGeYCXjO5ZmLW7Qdrge7Pm2r6tp2ZhNBWg49gAUjAggANYOOCIHXmBtYVrg7TtqRL6bnuiF7gOLTDnIMAyK62T4ZWhHtMRVEkbBG6dm+PZmCuLT8KROJkFCEDys4SDmvgrruoyMhej6-zgoKMZghCgjQvKNpaH4WAMJJ+C6OwSD-DpMp6iASYQNweCIsiIAIMIth8BJCB4BWMpAA)
