### ISSUE TITLE
cookbook example for XML dataset Java code

### ISSUE THREAD

**Issue by mgmcintosh92** [sparql-generate/sparql-generate#49]
I am new to this...

I have an XML file and TTL query file to works with the playground. I am looking for instructions/sample for how to write a very simple piece of Java code to perform the generation with those same inputs.

I am struggling to find any documentation for how to do this...

**Comment by mgmcintosh92** [comment]
What I can't figure out is, how do I load the XML or JSON file that I want to process?

**Comment by maximelefrancois86** [comment]
You can find some instructions here: https://ci.mines-stetienne.fr/sparql-generate/get-started.html
And the javadoc is here: https://ci.mines-stetienne.fr/sparql-generate/apidocs/index.html 

What you are asking is described in the section "Using a StreamManager and a LocationMapper", which refers to how this is dealt with in Jena:
http://jena.apache.org/documentation/io/rdf-input.html#streammanager-and-locationmapper
