### ISSUE TITLE
Don't HTML encode "/" if present in <?string>?

### ISSUE THREAD

**Issue by miranda-zhang** [sparql-generate/sparql-generate#50]
For example, if I have `?string="A/B"`
`<{?string}>` will generate `<A%2FB>`
but I'd prefer `<A/B>` in some case.

I know I can change my code to split it into 2 variables and use `<{?a}/{?b}>`

But it is not convinient in my case
https://github.com/miranda-zhang/cloud-computing-schema/blob/master/example/sparql-generate/gcloud/downlink_latency.rqg

Where I need `?type_slug` to be one of the following depends on the situation.

1. DownlinkSpeed/{?min_size}/{?max_size}/KB
2. Latency
3. DNSQueryLatency

So I can't simply change all `?type_slug` to 2 variables as it is not.

**Comment by miranda-zhang** [comment]
I end up replacing "/" in the string with "-" which doesn't encode to other characters.

**Comment by maximelefrancois86** [comment]
Dear Miranda Zhang, 

Syntactic sugar in URIs is interpreted as follows: 

```
GENERATE { 
  <{?type_slug}/ComputeService/gcloud/{?region}/{?zone}/> a cocoon:ComputeService
} 
```

is normalized as follows:

```
GENERATE {
   ?ze5f343zef3ze a cocoon:ComputeService
} WHERE {
  BIND( IRI( CONCAT( ENCODE_FOR_URI( ?type_slug), "/ComputeService/gcloud/" , ENCODE_FOR_URI( ?region), "/" , ENCODE_FOR_URI( ?zone) , "/" ))   AS   ?ze5f343zef3ze) 
}
```

There is no way to programmatically change the way ENCODE_FOR_URI behaves.
The only elegant ("kind-of") workaround I can think of here is to use Expression nodes:

```
GENERATE { 
   ?{ IRI( "{?type_slug}/ComputeService/gcloud/{?region}/{?zone}/" ) } a cocoon:ComputeService ;
```

--> which is normalized as follows

```
GENERATE {
   ?ze5f343zef3ze a cocoon:ComputeService
} WHERE {
  BIND( IRI( CONCAT( ?type_slug, "/ComputeService/gcloud/" , ?region, "/" , ?zone , "/" ))   AS   ?ze5f343zef3ze) 
}
```

**Comment by miranda-zhang** [comment]
Thank you for the clever suggestion!
But I'm happy enough with using "-", so I don't have to add `IRI` `CONCAT` code for each of the 9 URLs with `type_slug` in it.
