### ISSUE TITLE
Unable to import to IDE

### ISSUE THREAD

**Issue by ankushs92** [sparql-generate/sparql-generate#51]
Hello! Thank you for the effort in this project.

I tried to import sparql-generate-example which has a dependency declared as :

```xml
    <dependencies>
        <dependency>
            <groupId>fr.emse.ci</groupId>
            <artifactId>sparql-generate</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

The problem is that on mvnrepository, there is no such package that matches the group id fr.emse.ci . Could you help please?  

Thank you.

**Comment by maximelefrancois86** [comment]
Hello,

This is a snapshot (consider it beta) version of the 2.0. Not on maven central yet.

You can install is as follows:

1. download the jar https://ci.mines-stetienne.fr/sparql-generate/sparql-generate-latest.jar
2. install it with  the `mvn` command

```
mvn install:install-file  -Dfile=sparql-generate-latest.jar
```

Don't hesitate to give us some feedback :-)

**Comment by maximelefrancois86** [comment]
Just in case it fails to download required dependencies, you can also download the project from github

- https://github.com/sparql-generate/sparql-generate/archive/master.zip

and install it from there:

```
cd sparql-generate/sparql-generate
mvn install
```
