### ISSUE TITLE
Dealing with optional JSON fields when working with JSON files

### ISSUE THREAD

**Issue by ankushs92** [sparql-generate/sparql-generate#52]
Hello!
I have a case where my JSON looks like this :

```json
{
  "data": [
    {
      "Container Type": "Smart Playlist",
      "Container Identifier": 256000261,
      "Title": "Classical Music",
      "Added Date": "2017-06-02T00:00:19Z"
    },
 {
      "Container Type": "Subscribed Playlist",
      "Container Identifier": 256000517,
      "Public Playlist Identifier": "pl.7c33becaca34436388053264104dfd79",
      "Playlist Is Shared": true,
      "Playlist Previously Shared": true,
      "Added Date": "2017-08-21T22:38:36Z"
    }
]
}
```

As you can see, the first element has the field called "title", whereas the other one does not.
I am interested in getting the value of the field title, and if the title does not exist, then to supress the exception and ignore that field altogether.

Here is part of my mapping  : 

```
ITERATOR iter:JSONPath( ?playlistFile , "$.data[*]", "$.['Container Type']", "$.Title") AS ?playlistKey ?playlistType ?playlistTitle

```

I haven't used any Binding or any such.

Could you help me please? I would really appreciate it.
Thank you.

**Comment by maximelefrancois86** [comment]
Hi, 

The exception doesn't prevent the transformation to continue, it's just logged at DEBUG level to help you understand if something is wrong.

So if the title does not exist, the variable `?playlistTitle` is unbound (`UNDEF`). 
You can add a binding to put a default value in the case it is unbound:

```
BASE <https://ci.mines-stetienne.fr/aqi/data/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX iter:  <http://w3id.org/sparql-generate/iter/>

SELECT ?title
ITERATOR iter:JSONPath( ?playlistFile , "$.data[*]", "$.['Container Type']", "$.Title") AS ?playlistKey ?playlistType ?playlistTitle
WHERE {
  BIND( IF(  BOUND(?playlistTitle) ,  ?playlistTitle , "there is no title" ) AS ?title )
}
```

**Comment by ankushs92** [comment]
Understood, thanks so much.
