### ISSUE TITLE
Regarding performance

### ISSUE THREAD

**Issue by ankushs92** [sparql-generate/sparql-generate#55]
So we tested sparql-generate with 2 JSON files of sizes 1.2 MB and 9 KB each.  Our mapping file looks like this :
```
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX apple: <http://udaptor-apple.com/#>
PREFIX appleProp: <http://udaptor-apple.com/prop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

GENERATE {

  <http://udaptor-apple.com/tracks/{?trackId}> rdf:type apple:Song;
     appleProp:writtenBy <http://udaptor-apple.com/artist/{?artistName}> ;
     appleProp:inAlbum <http://udaptor-apple.com/artist/{?albumName}> .

  <http://udaptor-apple.com/artist/{?albumName}> rdf:type apple:Album;
              appleProp:albumName ?albumName.

  <http://udaptor-apple.com/artist/{?artistName}> rdf:type apple:Artist ;
              appleProp:artistName ?artistName.

  <http://udaptor-apple.com/playlist/{?playlistId}> rdf:type apple:Playlist ;

              appleProp:playlistType ?playlistType.

  <http://udaptor-apple.com/tracks/{?playlistTrackIdStr}>
       appleProp:inPlaylist <http://udaptor-apple.com/playlist/{?playlistId}>.

}

SOURCE </Users/ankushsharma/Desktop/code/spark-generate-example/resources/playlists.json> AS ?playlistFile
ITERATOR iter:JSONPath( ?playlistFile , "$[*]") as ?playlistData
ITERATOR iter:JSONPath( ?playlistData, "$.['Playlist Item Identifiers'][*]" ) as ?playlistTrackId

SOURCE </Users/ankushsharma/Desktop/code/spark-generate-example/resources/tracks.json> AS ?tracksFile
ITERATOR iter:JSONPath( ?tracksFile , "$[*]", "$.Title", "$.Artist", "$.Album", "$.['Track Identifier']") AS ?songsKey ?songTitle ?artistName ?albumName ?songId

WHERE {
  BIND(STR(?songId) as ?trackId)
  BIND(STR(?playlistTrackId) as ?playlistTrackIdStr)
  BIND(STR(fun:JSONPath(?playlistData, "$.['Container Identifier']")) as ?playlistId)
  BIND(fun:JSONPath(?playlistData, "$.Title") as ?playlistTitle)
  BIND(fun:JSONPath(?playlistData, "$.['Container Type']") as ?playlistType)
}

```

It was a bit surprising to see that although the linking and the abox generation was done in 20 seconds or so, however it took the program about 2.5 GB of Java Heap space to do it. I am a bit curious, if you could give me a brief on how the library reads files and mappings. I can then possibly try to optimize bits and pieces of it.

Thank you.

**Comment by maximelefrancois86** [comment]
Hi,

I would be interested in profiling transformation to enhance the performances. 

First idea to optimize the transformation:  put the second `SOURCE` before the iterators

```
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX apple: <http://udaptor-apple.com/#>
PREFIX appleProp: <http://udaptor-apple.com/prop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

GENERATE {

  <http://udaptor-apple.com/tracks/{?trackId}> rdf:type apple:Song;
     appleProp:writtenBy <http://udaptor-apple.com/artist/{?artistName}> ;
     appleProp:inAlbum <http://udaptor-apple.com/artist/{?albumName}> .

  <http://udaptor-apple.com/artist/{?albumName}> rdf:type apple:Album;
              appleProp:albumName ?albumName.

  <http://udaptor-apple.com/artist/{?artistName}> rdf:type apple:Artist ;
              appleProp:artistName ?artistName.

  <http://udaptor-apple.com/playlist/{?playlistId}> rdf:type apple:Playlist ;

              appleProp:playlistType ?playlistType.

  <http://udaptor-apple.com/tracks/{?playlistTrackIdStr}>
       appleProp:inPlaylist <http://udaptor-apple.com/playlist/{?playlistId}>.

}
SOURCE </Users/ankushsharma/Desktop/code/spark-generate-example/resources/playlists.json> AS ?playlistFile
SOURCE </Users/ankushsharma/Desktop/code/spark-generate-example/resources/tracks.json> AS ?tracksFile
ITERATOR iter:JSONPath( ?playlistFile , "$[*]") as ?playlistData
ITERATOR iter:JSONPath( ?playlistData, "$.['Playlist Item Identifiers'][*]" ) as ?playlistTrackId
ITERATOR iter:JSONPath( ?tracksFile , "$[*]", "$.Title", "$.Artist", "$.Album", "$.['Track Identifier']") AS ?songsKey ?songTitle ?artistName ?albumName ?songId
WHERE {
  BIND(STR(?songId) as ?trackId)
  BIND(STR(?playlistTrackId) as ?playlistTrackIdStr)
  BIND(STR(fun:JSONPath(?playlistData, "$.['Container Identifier']")) as ?playlistId)
  BIND(fun:JSONPath(?playlistData, "$.Title") as ?playlistTitle)
  BIND(fun:JSONPath(?playlistData, "$.['Container Type']") as ?playlistType)
}
```

**Comment by maximelefrancois86** [comment]
Hi, 

I added a commit that enhances performances a bit, you should use the latest version on github.

Below is the profiling results with the source being before/after the iterator. ---> this is simple query optimization, could be done automatically, no work has been done about this yet for SPARQL-Generate

The idea is that the second SOURCE is executed many times if it is placed after the ITERATOR... This does make sense only if it depends of the output of the ITERATOR

SPARQL-Generate uses mutli-threading, all the resources it can use to achieve the transformation faster. 

see that the size of heap space used is much lower when SOURCE clauses are one just after the other, and the garbage collector is less sollicited.

![thread-source-separate](https://user-images.githubusercontent.com/11416248/58271064-7cd87f00-7d8b-11e9-8817-9b03a53baaea.PNG)
![thread-source-together](https://user-images.githubusercontent.com/11416248/58271065-7d711580-7d8b-11e9-8e49-4dc05cbdb626.PNG)
**image 1: heap size and garbage collector calls for the original query (above), and the proposed query with SOURCE one just after the other, below**

A impressive hotpoint is java.lang.Throwable.fillInStackTrace, which is called whenever the jayway library cannot evaluate a JSONPath expression. Can't be optimized on my side, apart from looking for a better library.

![methods-source-separate](https://user-images.githubusercontent.com/11416248/58271067-7d711580-7d8b-11e9-8507-4946903fb092.PNG)
![methods-source-together](https://user-images.githubusercontent.com/11416248/58271068-7d711580-7d8b-11e9-9c8c-073fc7fcf8dc.PNG)
**image 1: time consumed by each method for the original query (above), and the proposed query with SOURCE one just after the other, below**

Best,

**Comment by ankushs92** [comment]
Thank you so much!

Btw, I notice that you are using Jayway-Jsonpath to parse JSON Files. I found that the library allows the developer to supress exceptions by using : 
```
com.jayway.jsonpath.Option.SUPPRESS_EXCEPTIONS
``` 

And then, this is passed to Configuration via : 

```java
Configuration pathConfiguration = Configuration.builder().options(Option.AS_PATH_LIST).build();
```

Could this be of any help to you? I tried importing sparql-generate directly to try this out but maven is complaining all around the place.

**Comment by ankushs92** [comment]
Also, just as a suggestion, in order to deal with peculiarities of specific libraries (let's say jayway-jsonpath), it might be better to let the user of sparql-generate API to have the freedom to define the configurations. For example, we can have a constructor like : 

```java
Configuration myJsonConfig = Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS).build();
Context context = SPARQLExt.createContext(sm, myJsonConfig);
```

Ofcourse you would then have to do this for each library you have. But this is a suggestion to let the developer chose configurations that are not the default ones that you use. It's not elegant, but it works.

**Comment by maximelefrancois86** [comment]
I checked with the `Option.SUPPRESS_EXCEPTIONS` option. Unfortunately exceptions are built anyways. It's just that they are not thrown.

Thanks for the suggestion 

```
Configuration myJsonConfig = Configuration.builder().options(Option.SUPPRESS_EXCEPTIONS).build();
Context context = SPARQLExt.createContext(sm, myJsonConfig);
```

Could you open a dedicated issue for this? I'll add that as a future todo

**Comment by maximelefrancois86** [comment]
I created branch [`sync`](https://github.com/sparql-generate/sparql-generate/tree/sync) with less asynchronicity, i.e. only:

 - to fetch multiple sources in parallel
 - for sub-generate queries

The heap size is indeed pretty smaller, but the transformation time is doubled (apprx. 40sec with your example query and files). Question is now: what is a good tradeoff. Isn't filling the available heap size what we actually expect? (i.e., use every possible resource)

![fork-version](https://user-images.githubusercontent.com/11416248/58284511-0ba8c400-7dab-11e9-9260-6fcffcc710c0.PNG)

Looking for good advice here.

**Comment by ankushs92** [comment]
This is how look at the trade off. For instance, my use case is that I need
to create a web application that allows users to give me their files, and
then I load them in graphs. In order to do so, I tell the user "Hey, I am
processing your file, please wait till I send you your result via
email(let's assume I need to send the user something)"
Well in this instance, the user can wait for 5-10 minutes, so speed here is
not really key. But, imagine I get 5-6 request from different users at the
same time. If we go through the async way, I would need to allocate 5x2.5
GB Heap space on a single server just to do this conversion. But since I
know the user can wait, I can just wait for additional 5 minutes to send
him the file via email, but atleast I get the benefit of low heap size.

So if we utilize everything in our heap(which is kind of what we are doing
with the async version), we simply cannot execute anything else. This also
creates a lot of pressure on GC. For instance, when I first executed
sparql-generate on my files, my max heap was 2GB. But then I noticed that
it the file was still being processed and nothing was happening. Then I
opened my activity monitor and voila, Java was taking 2 GB heap space. Had
I allowed my program to continue running, I would have run into the
infamous "*java.lang.OutOfMemoryError: GC overhead limit exceeded
<https://plumbr.io/outofmemoryerror/gc-overhead-limit-exceeded>*" .

Also, remember that realistically speaking, small companies and research
institutions are reluctant to allocate multiple servers with big memory.

My advice will be what you have already said. On the Java API reference here
<https://ci.mines-stetienne.fr/sparql-generate/get-started.html>, give the
developer the freedom to do async and sync both. You can have async as the
default behavior, and in one of the constructors, if the developer choses
to use the sync version of the program, all he has to do is to do this :

// create the query execution context
Context context = SPARQLExt.createContext(sm, Mode.SYNC); // or
Mode.ASYNC, which is default behaviour


But then, somewhere on that page, have benchmarks on memory consumption and
total time taken, explain both cases.

I hope that helps. Feel free to shoot me with any questions whenever you
need me. I for sure will have a lot of questions coming up.

**Comment by maximelefrancois86** [comment]
Just thought of another simple option, should have thought about it before!

The execution context admits a second argument which is the `Executor`.

By default, the executor is instantiated using `Executors.newWorkStealingPool()`: 

> Creates a work-stealing thread pool using all available processors as its target parallelism level.

You have more flexibility with other static methods of `Executors`. Here is are the results of a quick experiment for your use case on my laptop, with `Executors.newFixedThreadPool(nbthreads)` and making `nbthreads`vary. I report the min, max, avg, execution time on 5 consecutive executions:

- 1: min 38.6, max 40.9, avg 40.1
- 2: min 21.1 max 26.2 avg 22.9
- 4: min 12.9 max 23.4 avg 15.7
- 8: min 11.1 max 20.8 avg 14.4

Of course, these other executions use less heap space than the one with `Executors.newWorkStealingPool()`

**Comment by ankushs92** [comment]
How does the heap utilization with this? The hint is kind of there just in the name : ```Executors.newWorkStealingPool()``` .

Probably you can create an Executor with a fixed number of threads based on available cores

```java
        final int cores = Runtime.getRuntime().availableProcessors();
        final Executor executor = Executors.newFixedThreadPool(cores);

```

**Comment by maximelefrancois86** [comment]
see https://zgrepcode.com/java/openjdk/10.0.2/java.base/java/util/concurrent/executors.java

What `Executors.newWorkStealingPool()` actually do call:

```
return new ForkJoinPool
            (Runtime.getRuntime().availableProcessors(), 
             ForkJoinPool.defaultForkJoinWorkerThreadFactory, 
             null, true);
```

See `ForkJoinPool` class:  https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html

What I propose is to add a paragraph in the get-started.html page, and let the user (you) decide which Executor you want to use for your implementation. 

Still interested in reports on the performances, though.

**Comment by maximelefrancois86** [comment]
One last thing, about performance in your case:

You can optimize tremendously your quer(ies) if you start to understand how things are performed:

Each of the iterators are like `for` loops.  You are iterating over all the tracks in the 1.2Mb file for every track of every playlist (total of 245 times).

Plus, you do no join between the two files... In this case you are be better off writing 2 different queries ---> reduces the execution time from 20s to 592ms 🥇🥇🥇 

Now let's assume you want to join things between the two files. For example, generate RDF for tracks only if they belong to some playlist.

Then the optimum is: 

1. generate RDF from the one of the files, and keep this in a Jena Model
2. generate RDF from the other file, using that model as default graph.

Which executes in just 2s.

Below are the two queries:

```
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX apple: <http://udaptor-apple.com/#>
PREFIX appleProp: <http://udaptor-apple.com/prop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

GENERATE {

  <http://udaptor-apple.com/playlist/{str(?playlistId)}> rdf:type apple:Playlist ;
              appleProp:playlistType ?playlistType.

  <http://udaptor-apple.com/tracks/{str(?playlistTrackId)}> rdf:type apple:Song ;
    appleProp:inPlaylist <http://udaptor-apple.com/playlist/{str(?playlistId)}>.

}
SOURCE <http://example.org/resources/playlists.json> AS ?playlistFile
ITERATOR iter:JSONPath( ?playlistFile , "$[*]", "$.['Container Identifier']", "$.Title", "$.['Container Type']") as ?playlistData ?playlistId ?playlistTitle ?playlistType
ITERATOR iter:JSONPath( ?playlistData, "$.['Playlist Item Identifiers'][*]" ) as ?playlistTrackId
WHERE {
}
```

query 2: 

```
PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX apple: <http://udaptor-apple.com/#>
PREFIX appleProp: <http://udaptor-apple.com/prop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

GENERATE {

  <http://udaptor-apple.com/tracks/{str(?songId)}> rdf:type apple:Song;
     appleProp:writtenBy <http://udaptor-apple.com/artist/{?artistName}> ;
     appleProp:inAlbum <http://udaptor-apple.com/artist/{?albumName}> .

  <http://udaptor-apple.com/artist/{?albumName}> rdf:type apple:Album;
              appleProp:albumName ?albumName.

  <http://udaptor-apple.com/artist/{?artistName}> rdf:type apple:Artist ;
              appleProp:artistName ?artistName.

}
SOURCE <http://example.org/resources/tracks.json> AS ?tracksFile
ITERATOR iter:JSONPath( ?tracksFile , "$[*]", "$.Title", "$.Artist", "$.Album", "$.['Track Identifier']") AS ?songsKey ?songTitle ?artistName ?albumName ?songId
WHERE {
  ?trackId rdf:type apple:Song;
  FILTER( <http://udaptor-apple.com/tracks/{str(?songId)}> = ?trackId )
}
```

Hope it helps
