### ISSUE TITLE
Trouble parsing local files with CSV Iterator

### ISSUE THREAD

**Issue by TheMarmottin** [sparql-generate/sparql-generate#58]
Hello !

I have trouble executing queries on local files with 2.0. With previous versions, I put the paths as a string, like this : 
`ITERATOR iter:CSV("data/csvdata/sparqltest.csv", [...]`

However it doesn't seem to work anymore : trace tells me that initial values are empty, the only things generated by the query are prefixes

I tried using this syntax : 
`ITERATOR iter:CSV(<data/csvdata/sparqltest.csv>, [...]`

Interesting things happen then : 
- If I have a BASE address at the start of the document, the query execution will try to get my dataset at the address BASE + whatever I put on the iterator. 
Example : if i have both
`BASE <http://example.com/>` 
`ITERATOR iter:CSV(<data/csvdata/sparqltest.csv> [...] ` 
then it will try and find my dataset on <http://example.com/data/csvdata/sparqltest.csv>, which does not exist. 

- However, if I write no BASE address, but still put my iterator between <> symbols, it searches my source on local, everything goes well and I my dataset is found. The only problem with this is that I have to write the base on each URI generation. 

Is this intended, or am I missing something ?
Thank you very much.

**Comment by maximelefrancois86** [comment]
Hello Quentin,

Yes this is intended, the first argument of [iter:CSV](http://w3id.org/sparql-generate/iter/CSV) can now be a String (the CSV itself), or a URI (that identifies the CSV document)

If it is a URI, then the normal URI resolution mechanism (using a BASE) applies.

You have different solutions:

- use an absolute URI like `</home/themarmottin/app/data/csvdata/sparqltest.csv>
- define a URI-file mapping:
   - if you are using the jar, in a `sparql-generate-conf.json` document in the directory  of the query as explained in https://ci.mines-stetienne.fr/sparql-generate/language-cli.html
   - if you are using the java API, in a `LocationMapperAccept` as explained in https://ci.mines-stetienne.fr/sparql-generate/get-started.html

--> then you can tell SPARQL-Generate not to fetch http://example.com/data/csvdata/sparqltest.csv on the web, but that it can find it a certain location on your local file system

**Comment by maximelefrancois86** [comment]
Can I close this issue ?

**Comment by TheMarmottin** [comment]
Yes, absolutely. Thank you very much for the answer.
