### ISSUE TITLE
Generation of linked lists using hasContents and hasNext

### ISSUE THREAD

**Issue by Gonsco** [sparql-generate/sparql-generate#60]
Hi,

I have a doubt about how to deal with lists in some cases. Suppose we have the next piece of XML code:

```
<MaterialConstituents exp:cType="set">
  <IfcMaterialConstituent xsi:nil="true" ref="i16531"/>
  <IfcMaterialConstituent xsi:nil="true" ref="i16533"/>
</MaterialConstituents>
```

What I am trying to do is create a RDF linked list from this code. In particular, I am trying to generate the following one:

```
inst:MaterialConstituents_List_1
        a                  mat:MaterialConstituents ;
        list:hasContents   inst:IfcMaterial_6531 ;
        list:hasNext       inst:MaterialConstituent_List_2 .

inst:MaterialConstituents_List_2
        a                  mat:MaterialConstituents ;
        list:hasContents   inst:IfcMaterial_6533 .
```

In some cases, the items of the 'list' in the XML code have an index defined as a parameter with which to play (e.g., we can use it to define the position in the iterator). However, other times like this one does not. 

So, my real question is the following: Can this list be generated through SPARQL generate?

*I am assuming that the context of the iteration only exists within the ITERATOR iter:XPath form. So, is not possible to retrieve the current ‘position()’ or something like ‘following-sibling’ from the WHERE clause. I am right?

**Comment by maximelefrancois86** [comment]
Hi Gonçal,

The following [Example on the Playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSCLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCRrQRKuOMObl4BETEZhHHJsM0ZYV15o1Ylnj4hUWY9-3FtkooOQ+qTlfOxG5lZAHEyADkyBSIABVKMBpDIKBQAPxIGhaBwUGD3di4bo5DBaGAIADCwhkDiQOnQMiQ8IA3LIIRCHjQYA4ccTvCSDAtjpxTqsLiNdOjMcBIRhoABfSTk8GU6m0n4cJBQnzsGX8WSC2QkADyAFUFFjKLEjmw2S81vrlmd2FwEJJSFCHMI4BhBBBZARVD8ACIACgiUVw6jkfho7shNrtDoANNIQMxUdyMdjcfjCYyHMwAAIcJiCQFYBiOkAASgoVshmezEDzslUwIBgNVCm0B19-sDwftEHDUkj0cwsfpCaQRJJzFUUEEXZ5cbxBP7jI7FHbkeHo7RPfjU4HqYFUA7BaLVwgUM3UIYwnhkJpDil8tkAHUABL-EEUijOt2e3XVLmvKPLzG9tdJgB9Xo4SQADgHxDBA2PBwAGp2jzYVCxIKEYThChyzFF8PWZPVPyNMcV0nRNiQcICQLAiCoJPGCmgQy1kOhIYbAgAlBExS8ZQwiEsM9VRlE9M9JWlcNGIgZjWPY6U5yhKJICgdCkNlKSCzBQUKBAUMQBkbgIDANBuwgBw8AAbQAXU0uT4GQWxsgYGg8BADStJ0sAbJgOyjNwMyLOEQQ4C4JMWJM0A7S0ByqkWA0ziNZ5TXNJyIK0GRbAcqhITNBAKAAN0wBwtFxABeDt2n4FpZ28EQwCS2wipAdVAWUdwAA4O0hd4qAI39V2IpkMrxXB01qwEhjIdgGDkTctHYWc+ocXAyi0IahnUPKJugKbyrG3ASxzWqHBYjt3ghKhF06ic+wHCgFtwGRZlqpAMHQWdN1qrR2gANgAVjMdoO0KY7Tp-c7-2JK68puu6Owep6QAoF6Ozer6zDMP6juoQGYy6ojp1B67boQe7HtzOHoFej7PoAFjKyM0ZOkczr-Hqwa0CGCahonntJhHyc+6nCiob9MeBnqHHEJznBhBywF8-zAqQY12X4DKnICqq-FLBz3N4LQ2IJXFmGVwVzJACCIG4PBYAQfbNIQYRbD4HKEDwT7BSAA) implements your use case. 

Note that I just fixed a small mismatch between the XPath iterator and its documentation: last output is `isLast` and not `hasNext`. Corrected on the website and in https://github.com/sparql-generate/sparql-generate/commit/dfc04c1ebdd1045a1f783762a7dc62262c4df9b3

Please use the latest version of the JAR or the source.

Just one point: that's not a RDF list. For RDF lists, see the adapted [Example on the Playground](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSCLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCRrQRKuOMObl4BETEZhHHJsM0ZYV15o1Ylnj4hUWY9-3FtkooOQ+qTlfOxG5lZAHEyADkyBSIABVKMBpDIKPd2PoHuwRroMFoYAgHBReqoSICABQAfgQWgcSAAlBR+LIIbj8UgKDBIbhujkEUiAMLCGQEnToGRIFEAbjJENpNBgDhZXO83IMC2OnFOqwucMwiIQwGxGGgAF9JKSZOrZCQAPIAVQUTMosSObBlLzWluWZ1hCEkpAo2IcwjgGEEEFkBFUPwAIpiIlFcOo5H4aDi3R6vQAaaQgZj0+FK0XspCc7nMAACHCYgkBWAY3pAxOd2ILRYghNkqmBAMB+oU2gOYYjUfdnog8akieTiuZrPTmYczFUUEE-cZCDTSA54t7FB7ifHk4ZqaHc4z4pzaqgvbLJBdVwgLr3LoYwhR2PxvWFSFkAHUABL-EH830BoPm6pw15J9dBzZLcRwAfV6SlQOAAkMBxS8HAAanaQlNQocskBofEKBrcEKE-QNJQtP8bSnDdgPnLkHHAyDoKQWDsXghCmhQp0j2xDCIBsCA50EJEfg4KkcIhfCg1UZQgwAQhvBw7wJeN2KGLieL4gSlxdKJICgbC0LYnx2EEiEPz9AiACM9kgTFDxdPECWw2R1QoEBYxAGRuAgMA0EVCAHDwABtABdZzNPgZBbGyBgaDwEAnJctywDCmAIp83AAqC4RBDgLhxQcbi-NAD0tCiqpFitM4bWee0uAQGKYK0GRbCiqhsQdCgADdMAcLRWQAXl7dp+BaRdvBEMA6tsXqQENQFlHcAAOXtsXeKhSKA4dsooB02VwPMJsBIYyHYBg5D3LR2EXTaHFwMotF2oZ1E647oFOobDtwStiwmnKHxAd4ISoVcVpnTcKKpa7cBkWYJro9BFz3CatHaAA2ABWMx2l7Qo-oBwCgfI7cuQ2zrwch3toZLCg4d7BGUbMMwMd+6hsZTVaQPFQmtGJhAoYwGGQAp6B4aR5GABZBsTBn-onQHZxB9nOe53n+agQWUeRsXCioADmdxtbKPEGLnAwqKwHSzLsu421ZX4B0Yqy0a-CrKLEt4LReLnVlmBt9VApAGCIG4PBYGRbsQAQYRbD4drqtwZH1SAA)


*You assume right: the position/hasNext functionality is currently specific to (some) iterators. there is no means to get it in the WHERE clause. However, a function to get this position could probably be implemented. I already know the URI of the function (see https://ns.inria.fr/sparql-template/#template6 ). If it would enable nice use cases for you, please tell me.

**Comment by Gonsco** [comment]
Thanks Maxime,
Using now the latest version of the JAR, and following the implementation form you provided in the example in the Playground, I have solved the problem.
