### ISSUE TITLE
bindings not passed to sub-sub-query

### ISSUE THREAD

**Issue by Gonsco** [sparql-generate/sparql-generate#62]
Hi,

After have changed the JAR version from 1 to 2, I have noticed that some things have stopped working in SPARQL Generate queries that worked well for the previous version, if I am not mistaken. One I have observed is when using identifiers to find matches in the path. Something like:

`BIND( fn:XPath(?source, "//term_2[@id='"+?Term_2_ID+"']/@name") AS ?Name ) `

Has there been a change in the syntax or query processing way that invalidates this form?

The following <a href="https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAHgM5i40A8AFkkgA64D0fAO7CAdIIDMIgPYYA5nwBMABiUBGPlQCyAGQDKAY3YQAtjADEAPhoAdAHbFy1GgEskmFhy68BE52GlyfAzcMBgoCAC0shC2mDBufK6YfBZ2DpS0ULYenDz8QuJ+AfLBoeFRMXEJWSlppBk0EHQ5XvlNMMbcCBAi+lLGtbZ2AOIkAHIkRACCACokdsB21m7NtlKQqo3N3BhS3DQA-GMdEDQA3HYAvna6APIAqkQAwiRsud587Z3dvf2fdB0uj06MYEFYprpDgwpHAMPoIHYKHNpjNbkQXG4MLgqAR4uwABQHaGw+EAGhsIAEmOMAH11NSaQo+AABPzWEA0ACUNAhhxmmFpChpFAAInYAOoACUmrwWSyQACEKGMRfiaFlsbikASiTC4RByeyqQLGQBtVlgAC8AHJ2QBqA78jCC4Uiu3s60AXRZthO7O5vKOJy5VxApJAvuMEDAaEwzggDDwps94cgsEQSFkGBg3HYeBAYYjJzAWZz7ETuGTqak+jgUdsSAYECQSdAsOc+febQB3x6fQGXyBIhBCELUbAzniWG4EHzOa6zn08WcUlsfBHhYYSAwzlssnzrAOI5oADdMAwV7ZLezVCIlOzGrY+hO99eQPcZmQIgAOdkHVK2KwDKqAByxASaCguFaN4qEaqRIHYrB8MBAHgc6jJQW+qiwRykYQG+UwIFAGDRnBICXCmIBbiRHR4LACBNuGCBSLI3RnqOuAAKyXEAA">example in the Playground</a> tries to show better what the problem is.

**Comment by maximelefrancois86** [comment]
Hi Gonçal,
In your minimal working example, there is no root element in you XML, therefore it's not valid and cannot be parsed (cf. Explanation in the log)

**Comment by maximelefrancois86** [comment]
Then, have you been developing in Java recently to use `+` to concatenate strings ? ;-)

 `+` is only defined for numeric literals in SPARQL 1.1  https://www.w3.org/TR/sparql11-query/#OperatorMapping 

As a matter of fact, your example works, and thanks to you I learned something today: Jena extended the `+` operator to strings (string concatenation), which is perfectly legal as per SPARQL 1.1 Section 17.3.1.  This is also the mechanism we used for the Linked Datatypes 
https://ci.mines-stetienne.fr/lindt/playground.html?example=0-ucum


Anyways. [The following example, adapted from yours, does solve your issue](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAHgM5i40A8AFkkgA64D0fAO7CAdIIDMIgPYYA5nwBMABiUBGPlQCyAGQDKAY3YQAtjADEAPhoAdAHbFy1GgEskmFhy68BE52GlyfAzcMBgoCAC0shC2mDBufK6YfBZ2DpS0ULYenDz8QuJ+AfLBoeFRMXEJWSlppBk0EHQ5XvlNMMbcCBAi+lLGtbZ2AOIkAHIkRACCACokdsB21m7NtlKQqo3N3BhS3DQA-GMdEDQidjSXW7hrkArXO3uHiyAAEhAICFLWIDQA1D8AOoyBBgH40AC+ZzsELsugA8gBVIgAYRIbFy3j47U63V6-WxdA6XR6dGMCCsU10hwYUjgGH0EDsFDm0xm8KILjcGFwVAI8XYAAoDrT6YyADQ2EACbnGAD66llcoUfAAAn5wQBKGhUw4zTDyhRyigAETsgNek3RCyWSAAQhQxibBTQsrz+UghSK6QyIJKfjKDcqANrqsAAXgA5D8-gd9RhDcaTQCQJGALpq2wnH7a3VHE40TUwkDikBZ4wQMBoTDOCAMPDBtOlyCwRBIWQYGDcdh4EAlssnMAdrvseu4RvNqT6OAV2xIBgQJAN0D05y9zFtIm4np9AY4kkiMkIfsVsDOeJYbgQXtdrrOfTxZxSWx8I-9hhIDDOWyyXusA5HjQABumAME+tjhj8qgiEo4IxH0Z4-pBICIjMZARAAHD8BypLYrC7FISC4awSqqLhywkUG9x+MhqgqAGqRIHYrB8KRxFKtREZQfRvzlhAyFTAgUAYJWDHMXwBFESAEJNiAH4iR0eCwAgC6ll8sjdCBx64AArBCQA)

**Comment by Gonsco** [comment]
Hi Maxime,

It is true, I have added the root node in my simple example (that I have created from scratch) and it works. However, this is not what happens in a query I have implemented weeks ago and that follows the same structure/mechanisms, but is much more complex. Knowing that the contactenation mechanisms is still valid in the new JAR version, I will try to find out what really happens and provide the feedback as soon as possible in case it can be useful :)

**Comment by maximelefrancois86** [comment]
If it has something to do with str concatenation with `+`, check that the passed arguments are actually strings. Jena did not extend + for string+integer for example

**Comment by Gonsco** [comment]
Hi Maxime, 
I think the problem is not related to the concatenation issue. I have modified the example to reflect the problem which seems to be related to the fact that the new version does not like absolute paths in nested iterators. Could it be? For example, the next iterator:

```
GENERATE
{
  ex:node1 ex:prop ?Name4 ;
}
ITERATOR iter:XPath(?source, "//root/term_2[@id='100']/term_3") AS ?Term_3_B
WHERE 
{  
  BIND( "Alex" as ?Name4 )
}.
```
produces the following result:
`ex:node1  ex:prop "Alex"`

However, when it is included in a loop that iterates it (one time), it does not. see the <a href="https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAHgM5i40A8AFkkgA64D0fAO7CAdIIDMIgPYYA5nwBMABiUBGPlQCyAGQDKAY3YQAtjADEAPhoAdAHbFy1GgEskmFhy68BE52GlyfAzcMBgoCAC0shC2mDBufK6YfBZ2DpS0ULYenDz8QuJ+AfLBoeFRMXEJWSlppBk0EHQ5XvlNMMbcCBAi+lLGtbZ2AOIkAHIkRACCACokdsB21m7NtlKQqo3N3BhS3DQA-GMdEJsA3HY0VzSjE9NzS0iLttc2K7hrG1u4O3uHx8YIAoaBcXtcAL6XN4UOb3ADyRBcbgwuCoBHi7AAFAcGFI4Bh9BAADQ2EACXZSJB8ZHGAD6CgA2gABPwAXgA5NYQABqA4zTB0hS0igAEW5XPZAF1qQLaeIuSSuTS5XwWWAuTQAJQ0Ka6Q78jB08T62XiYUiqFXMwwyazBFI9xojHYg2CxVkmWG+nMtmcnl82VC0XikBSz1GhWk5XiVV+DXa3Umr3GgPJ82PADqAAlJiQbEMno9lgAhChjEWYmhZVHopBYnF4gnE0nkqSU8P0jviH1gDlc3muuXmkNhpm2E5chN6o4nYGay2vGhmUvlyvVp11l2m90CaOq8eAyc66cAoFax7gkRQhe3W0PAvPV7LJofdanb6-fYzwHG0GL5a3vc8wFssj7-kgz6rG+mwvp+-wnAALCCC5XMskJgqhSA2vCiJJCiG71ri+KEjufAUlSyqMmqHKqCoYbRkeiapkatLFkWSDZrm+bLKBqEYdcPFICuFaklM3R0BqMAMPBgJIfO-GYZei75q86GYdhdq4ciNbOg2xHNlyrbtpRjHToO8oFpxpDcYWIFCWWIlcgQEDIhqTGnsa8loVetjobocIAKpEAAwnmnh5AI7SdN0vT9HwUVdD0dDGAgVhMURTZ2BpMz2nhOmbnpTakeRHbqCZIDupRsbqiAWrHkmgoNfS6a2FZeYLI8wlrtkBHYhlJEtmRbYUYGPZ9v6g5BmKErSmOE4gFOMnvvJ6EVSAB4QGAaCYM4EAMHgDKSkS4DQPAyCyBgMDcOweAgGtG1gBdV3sPtuCHcdYBSPocCArYSAMC5B2gPizi3bk3jxXQHSJbFAwJTFyUIGtgJgM48RYNwEC3VdXTOPo8TOFIth8Ija0MEgGDOLYsi3awByIzQABumAMITtislyqgiEoGoxH0qPUxzIABTMZARAAHFyBypLYrDkTLyysMqqgKxBSBK4GLi9pzKiGakEEFqwpWqxrXrAmyOs87VG1C2JUAYJtXIy8pivRlrQu0aoGo205eOhDVKQu2CisdgoMtG-LIDgkdIDkw7HR4LACAA8dCBSLI3TM0juAAKzgkAA">modified example</a>.

**Comment by maximelefrancois86** [comment]
Yes, check what term3b contains

**Comment by Gonsco** [comment]
Apparently nothing, which is consistent with the warning message. Am I missing something?

**Comment by maximelefrancois86** [comment]
Oh my!  no you are right,  the following [minimal example illustrates what goes wrong](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAHgM5i40A8AFkkgA64D0fAO7CAdIIDMIgPYYA5nwBMABiUBGPlQCyAGQDKAY3YQAtjADEAPhoAdAHbFy1GgEskmFhy68BE52GlyfAzcMBgoCAC0shC2mDBufK6YfBZ2DpS0ULYenDz8QuJ+AfLBoeFRMXEJWSlppBk0EHQ5XvlNMMbcCBAi+lLGtbZ2AOIkAHIkRACCACokNMB2NI3NdKoruNw0APwMUnAY+hBLNKMT03MLdtZuqwobW7v7h8e2y8tnk7Pzi0NIy01cHRxA8dnsDkcTssAL40EQnWHw2zQuy6ADyAFUiABheaePICdqdbq9fp8IldHp0YwIKxTXRg55HEAAGhAtg6EDAaEwzggDDwAG0ALpsyCwRBIWQYGDcdh4ECs9mcsDS2XsAW4EViqT6ODGGJIBgQJBC0AHZwK3Lecl0DqU0kDCkk6kIJUGsDOeJYbgQBWyrrOfTxZxSWx8V1KhhIDDOWyyK0QBAIKQgaGikDRjAQDp4WAIY1slOyboANyTeAArNCgA).

I'll check that right now. keep you posted

Will edit the name of the issue though.

**Comment by maximelefrancois86** [comment]
please pull the latest version. solved also on the website

**Comment by maximelefrancois86** [comment]
still a little issue with your query though. I'm on it

**Comment by maximelefrancois86** [comment]
(please confirm :-) )

**Comment by Gonsco** [comment]
Ok, now is working using the full path :)
Using a variable instead of the full path there is no error but it does not give results either.

**Comment by maximelefrancois86** [comment]
I don't get what you mean. can you provide an example ? (won't do it today)

**Comment by Gonsco** [comment]
In the same <a href="https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAHgM5i40A8AFkkgA64D0fAO7CAdIIDMIgPYYA5nwBMABiUBGPlQCyAGQDKAY3YQAtjADEAPhoAdAHbFy1GgEskmFhy68BE52GlyfAzcMBgoCAC0shC2mDBufK6YfBZ2DpS0ULYenDz8QuJ+AfLBoeFRMXEJWSlppBk0EHQ5XvlNMMbcCBAi+lLGtbZ2AOIkAHIkRACCACokdsB2NDZuzbZSkKqNzdwYUtw0APxjHRBbIkvLNKMT03N21kiLtlcrTbjrm9u4u-tHJ8YIAoaBcXq8rmYIlDoTDYXD4QjEUjkSjLldHjdJrN5kMkI9nuCVo93p8zt9fgdjqdxCC0ei8UgzCSNmT3hTgYcZphjAB9cQ8gBCtLBr0eAF86Y8KHM7gB5IguNwYXBUAjxdgACkODCkcAw+ggABobCABHspEg+EreQoANoAAT8AF4AOSqFQugC6Vu5fOsIAAlDQprojlyMLz+QKHgyAOoACUmJBsuPxyzp6YZAooYwAIhqTVNunRVP6aDAGP9qTQg+DHvWRfSxaDCctISiO52u934Rmrpi7jj608+8PmV82XtKQCIAAWYWE4dMtYsraT-Yc8O82eChd1pASxtSmWzeWK9yq9Varc8hTG-0+iO3h3Ot0e73Wv2B4Ohzm+nfRqmSAJkmKbDsA6aNpmjzZnmBb+kWTQKGWFZVoC84BqOB4tq27Y9vhBGEVCdKHpm0pYjMZ5JMql5IJq2q6vqRommaUgWo+Nr+kGIZhr64gxiBpBgSOQGwfmJoEBASpljxVKAsCmG4s2diHrosoAKpEAAwsmnh5AI7SdN0vT9HwhldD0dDGAgViyTqeoGnY5Fygq1EqmqdFavZTH3qafDmpan7qJ+yEgL5IV8I6YBltxv43puvoKDyFC5nYgnJgsMZiQWWTuVeDEOcxD7+WxgWJS+YCuv6ADUf5PklKXVf6XqRbYpxcT+aFkoph5hSAbWAmAaCYM4EAMHgtqeoa4DQPAyCyBgMDcOweAgH1A0QGAC1Lew424JN01gFI+hwICthIAwUkTaAerOKtuTeGZdAdBZJkDOZxlWQgfWDc48RYNwECrUtXTOPo8TOFIth8F9fUMEgGDOLYsirawhxfTQABumAMJDthOv6qgiEoZYxH0YBI7IBMgOpMxkBEAAc-qHKktisAFrOPKwQWcwy3OJS4lWEyoD6pHiuKsBxPKqLz-P1YL1PuiTIA0Bt1NFlAGCbf6rOtnLkYK8LpYq2r-oEGDoTRaausrJLIWs5LHMgGKU0gPDWsdHgsAIJd00IFIsjdNj324AArGKQA">last example</a>, I thought you meant that when you said you were in it.
That is, the following iterator is not working (assuming the query is well written):
`ITERATOR iter:XPath(?Term_2, "/term_2[@id='100']/term_3") AS ?Term_4_B`
That is, the following iterator that uses the full path, now is working:
`ITERATOR iter:XPath(?source, "//root/term_2[@id='100']/term_3") AS ?Term_3_B`
It is clear now?

**Comment by maximelefrancois86** [comment]
In your example, `?Term_2` is bound to `"<?xml version=\"1.0\" encoding=\"UTF-8\"?><term_2 id=\"100\"/>"^^<http://www.iana.org/assignments/media-types/application/xml>`

So it is normal that `iter:XPath(?Term_2, "/term_2[@id='100']/term_3")` returns nothing

**Comment by Gonsco** [comment]
Ok, so it is just been a misunderstanding of mine about how the processing of the queries works. I thought that variables include all the internal content, not just the node. I thought that if the global variable '?source' contain everything, those generated in an intermediate way also (downstream):

```
<term_2 id="100" name="Alfred">
       <term_3 id="101" name="Picard"/>
</term_2>
```
If this is right, then we can close the issue :)

**Comment by maximelefrancois86** [comment]
It *does* retrieve all the internal content, it's what you queried for 😁

**Comment by Gonsco** [comment]
Indeed ¿O_o you are right, sorry. I confused the node I was accessing to in the iterator (through term_1).
