### ISSUE TITLE
Make XPath function/iterator parse documents into a DOM, regardless of wether valid XML format

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [sparql-generate/sparql-generate#65]
Currently, the XPath function only works on documents that follow rigorously the XML syntax. It would be much better if it could parse HTML5 (for instance) into a DOM before applying the query. That would enable a lot of extremely convenient screen scraper use cases.

**Comment by Antoine-Zimmermann** [comment]
It seems that this kind of functionality would require a first step in cleaning the HTML to get a proper DOM, then proceedings as before on this DOM. HTMLCleaner or JTidy are 2 Java libraries for cleaning the DOM.

However, currenty the XPath iterator is dying with medium-sized file (e.g., https://www.emse.fr/~zimmermann/CV.html -- 265 kB), so I'm not sure it would scale well.

**Comment by maximelefrancois86** [comment]
solved.
