### ISSUE TITLE
what does n't work ?

### ISSUE THREAD

**Issue by maximelefrancois86** [sparql-generate/sparql-generate#67]
https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAlkhLjQDwAWSSADrgPS8B3AMx0wAOgD2GAOa8AzlxgYUCALTSIAO0wxGvBpl4A+ADqbi5ajQxgoc5u049+A12OGSZvAEwAGf7y+AIy8NlCqcgDGbBAAtjAAxKbmpJS0kRixDhzcfIJukaISkaoZsZ6yhWDFpZnGZmYA4iQAciREAIIAKiQ0wDRmNDQA-DEICBI0MDRluCTeQQD6BJhyEpoA3INDO7tDYfYIMABGEAgjSkh0ckg0YtvbzW2dPTQAFKNnEwCUfds7n3Gk1YcgYjAwRiGw1BnEwmhgsQgdwGmiGAF8aBQei8APJEeiMXAAKQAyjiWgRdGwPjDwTQADQmEAAEgA2gAqAC6TPpAxZYhaCIgTJovw6JJGtMwEmOACsIJFbtCwXChXcGpo0WYse1uniCUxSeTKUhqY5cvwIAAPBFcBAQMSRCSxXixOByCBwcqytaaIyMlkc7kgXlM5liDoYK43Hl88MklUYJliiXDARSADWFyj1yVUow8MRZgAQhQWgARN5Dc3OXjWx3O3j9UgEAAyHQAwiQq8NLrmGXzB6GQIsRb80ZDxSMxhNRWYQyBCxAwGhMHQIHI8KzOfTwNB4MhpBgYFw2HgQAul2Ajye2JvcNvd9VIl6tEgPUgt6A4Bg6OecrW1q2vaDYum6HpemIPrrAuNy-po0jnqyJhJqiOzACh-x7EyXQMPaTLMEyHRcBIQI0EEQQ0B2GAQAIPKYWhex8pG0ZIARfJEOsMAIGANAdJokAYL69GoUxQxMkQ0DsUyFKNIsADsviLEIABsIlYbsTIJrCSZ4DQyGiWJuz9AxRlGTJQrSSALQQHQ5yRrEcHrNIIqmWZ6KMoZ7kmV57k7BZRZ6UyxZwAAXqFfE8fBrm+UZaKeRpYk+Yl7kBcKQUgAAsnQ0QwGcVGkQgdCaHIMUpXsWqxTsO5uUxTLlroEA4lAADqmZWUEACcKmdUytU0PF-UYVV4kgLhSD4RlNl2XxmROQh6mMdhIAsbmVmcacUY0F0MQSNUNE0JlkQdtxCCLeZICSVAVkkossmLH4QRKQArEE51iVpibsQZ5XGQMI1mWlVnTfZc1IBgzl9QDuyVeVNUA-VjXNW1GAZlZfi+L1ID9YNvnDeVOF4elhEgAAElo2A0K2ShOrEfHHMcEhsSG-WaStOYxlNMBsF6NDFqdNA4popowJoaMswjl1SVNBByZ13iLEE3jye9dUgNp4LfazSX-b9H3WZZGXk5olPUxgtP04zzO60tcXa0M8MEyADWMMj7UZUEAAcz0q9jvmw5o3KoQuiJgHQuhYFwEDniedo5bodDrLw0GaCA8Xfr+-5OHkQGxHaDq066EjrKoAjcRmqyOnIABusHg8ViH4IKiL0sWdBRmwNAuxA9LlhAVJd419LZXIoLrPSJAAGodIPjD0iSmDVzlwqoSDs2OeDzn0l1Qi+Kovie-vz30o93j74f3jH8RhWTBR2-dZ1+-yaoCz0i04odAxIXhZFYDwffu995BBfr4ek9Jr5kTvl1HqT8X5BHAe3GgZApCRBXmYFYjAComxgGAABe9fAqX3t4e+nVH6+GfgfcBJFIHEOgY-CiqgupvxgNXLADEOhHFRMWfumgAFn18EIRhx8qE33IrQh+jDgFMMFKw9hnCaAkhiIoGw99vCCIYV7Ehh9yFwJEZAgALPfeSwDfD8OPjIthqESDXiUIdBg0Qvh4P3vQ+SYCIGziCIYrqxiiFH2YbI1CDUl68RJE6TgfD96EIIW46hHjj7eJMc-IQ8COiIOQebNBmgiRCjkJiDAAhipOIEYw1xXVOomO0Z7PRcSjGJNUMkhBGAkEoMyUSCQbBUQAE0JBwAQkUx+3hDHVNvipIx-D9G6IsQxDsbAlD2lyeWOAFcAHPUYfgoQMTRFBFGd48ZujUlNPSaghiJA4AaG0FRVUvCd4TOKZ4zZkDSmdXkmfJWkj-GWLMKTJQv5fQKOiLEMEKzYECIeR4p5LzGGvPge-Ekn9ULG1NjTZ0lsmbb09sk8+jCNldWVmsoBYCQ7LnDkgSO0d8CMCtEgXgkQa5px3CAOC-dYh4FgAgD0u4JjSHtNXM4eBnpoiAA

**Comment by noorbakerally** [comment]
Just a hint but not sure, there are 2200 characters in the URL. I think there is a limitation on the number of character for GET request both on browsers and servers as well. This StackOverflow anwer [1] says the defacto limit is 2000. As it says, this is purely an implementation issue as the RFC itself doesn't place any limit.

1. https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by maximelefrancois86** [comment]
Thanks Noor, but 2200 is fine for the hash-part of the URL.
I didn't post here the most informative issue! 
I create this issue during a tutorial to illustrate how one can use a minimal working example to open an issue.
What was not working is: there is an error in the query. This one works as expected

https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAlkhLjQDwAWSSADrgPS8B3AMx0wAOgD2GAOa8AzlxgYUCALTSIAO0wxGvBpl4A+ADqbi5ajQxgoc5u049+A12OGSZvAEwAGf7y+AIy8NlCqcgDGbBAAtjAAxKbmpJS0kRixDhzcfIJukaISkaoZsZ6yhWDFpZnGZmYA4iQAciREAIIAKiQ0wDRmNDQA-DEICBI0MDRluCTeQQD6BJhyEpoA3INDO7tDYfYIMABGEAgjSkh0ckg0YtvbzW2dPTQAFKNnEwA0I3IMjAwAEo+tsdp9xpNWP9OJgjENhjDAZoYLEIHcBpohgBfGgUHovADyRHojFwACkAMqEloEXRsD5IzA0b4mEAAEgA2gAqAC6bN+bPZYhaqIgbJoII6lL+AMwEmOACsIJFboi5RgUWi7g1NNizPj2t1iaSmFSaXSkAzHLl+BAAB6orgICBiSISWK8WJwOQQODlRVrTRGVkcnn8kCCjliDoYK43AUDaOUjVsqUy4YCKQAawuceuaqZGDMACEKC0ACJvIY25y8B1uj28fqkAgAGQ6AGESNXhpcCyyk0Oo4sJSDsfDpSMxhNJWZIyAtRAwGhMHQIHI8Jzed9wNB4MhpBgYFw2HgQAul2Ajye2JvcNvd9VIv6tEhfUgt6A4Bg6OecnWDpOi6jaet6vr+mIgbrAuNy-po0jnpyJjFliOzAChYJ7GyXQMC6bLMGyHRcBIkI0EEQQ0J2GAQAIAqYWhexJrG8ZIARSZEOsMAIGANAdJokAYEG9GoUxQxskQ0DsWytKNIsADsviLEIABsIlYbsbIprCxZ4DQyGiWJuz9AxRlGTJYrSSALQQHQ5yxrEcHrNIEqmWZOKsoZ7kmV57k7BZaJWSWcAAF4hXxPHwa5vlGdinkaWJPkJe5AXinpbIALJ0NEMBnFRpEIHQmhyNFyV7PqMU7DublMWyFa6BAhJQAA6jmVlBAAnCpHVsjVNBxX1GGVeJIC4Ug+HpdZtn2ZkTkIepjHYSALEFlZnGnHGNBdDEEjVDRNAZZEnbcQgC3mSAklQFZlKLLJix+EESkAKxBGdYlaamekGWVxkDMNZmpVZNl2Xxs1IBgzm9f9uwVWV1X-XVDVNa1GDZlZfi+D1IB9QNvlDWVOF4WlhEgAAElo2A0G2SjurEfHHMcEhsZGfWact+YJpNopsP6NAlidNCEpoVowJoaMswjF1SVzBByR13iLEE3jyW9tUgNpgLsd9i1GUlOt+YDk3k5olPUxgtP04zzN-T9Oyw-rQzwwTID1YwyNtZNQQABxPSr2O+fb-KoQuaJgHQuhYFwEDniezrZbodDrLw0GaCAcXfr+-5OHkQGxM6rq016EjrKoAjcdmqxunIABusHg0ViH4KKaLfCWdBxmwNCuxA3wVhA9Jdw13xZXI-zrN8JAAGodIPjDfJSmDV9l4qocDM2OeDznfJ1Qi+Kovhe-vT3fA93j74f3jH8RBWTBR29dR1+-yaoCzfC00odAxwVhRFYDwffu995BBfr4b43xr5kTvp1bqT8X5BHAe3GgZApCRBXmYFYjB8omxgGAABe9fAqX3t4e+HVH6+GfgfcBJFIHEOgY-CiqhOpvxgNXLADEOhHCxCWfumgAFn18EIRhx8qE33IrQh+jDgFMNFKw9hnCaCUhiIoGw99vCCIYd7Ehh9yFwJEZAgALPfeSwDfD8OPjIthqESDXiUAdBg0Qvh4P3vQ+SYCIGziCIYzqxiiFH2YbI1C9Ul68UpO6TgfD96EIIW46hHjj7eJMc-IQ8COiIOQebNBmhyRijkHiDAAgipOIEYw1xnUOomO0V7PRcSjGJNUMkhBGAkEoMyeSCQbAsQAE0JBwAQkUx+3hDHVNvipIx-D9G6IsQxTsbAlAulyRWOAFcAFPUYfgoQMTRFBFGd48ZujUlNPSaghiJA4AaG0FRTAKJeE7wmcUzxmzIGlI6vJM+StJH+MsWYUmShfxBgUdEWIAIVmwIEY8jxzzXmMLefA9+lJP6oWNqbGmHpLZM23l7ZJ59GEbM6srNZQCwEh2XOHJAkdo74EYPaJAvBIg1zTjuEAcF+6xDwLABAvpdwTGkC6auZw8BPWxEAA
