### ISSUE TITLE
 Could not look up function http://w3id.org/sparql-generate/fn/CSV

### ISSUE THREAD

**Issue by nimonika** [sparql-generate/sparql-generate#68]
When I try t run the SNAPSHOT 2.0 jar, it gives me an error that it could not look up  Could not look up function http://w3id.org/sparql-generate/fn/CSV

**Comment by maximelefrancois86** [comment]
Hello,

Iterator function [`iter:CSV`](http://w3id.org/sparql-generate/iter/CSV)   is probably what you are looking for (used in `ITERATOR` clauses), not to be confused with binding function.

http://w3id.org/sparql-generate/iter/CSV

Is that helping?

**Comment by nimonika** [comment]
I am not sure how do I resolve the issue. I can send you the full error trace

**Comment by nimonika** [comment]
`43:18,102 ForkJoinPool-1-worker-3 DEBUG fr.emse.ci.sparqlext.stream.LocatorURLAccept:73 - File not found online: http://w3id.org/sparql-generate/fn/CSV
43:18,102 ForkJoinPool-1-worker-3 WARN  fr.emse.ci.sparqlext.function.SPARQLExtFunctionRegistry:128 - Could not look up function http://w3id.org/sparql-generate/fn/CSV
43:18,103 ForkJoinPool-1-worker-3 WARN  org.apache.jena.arq.exec:78 - URI <http://w3id.org/sparql-generate/fn/CSV> has no registered function factory
`

**Comment by maximelefrancois86** [comment]
The query contains an error. I need to see the query.

**Comment by nimonika** [comment]
The idea is to basically generate a subject IRI with the animalID

**Comment by nimonika** [comment]
`PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX fun: <http://w3id.org/sparql-generate/fn/>
PREFIX cow: <https://data.agrimetrics.co.uk/ontologies/animals/cow/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

GENERATE {
 ?animalIRI a cow:Cow.
}
SOURCE <./data/test.csv> AS ?source
ITERATOR iter:CSV(?source) AS ?entity
WHERE {
         BIND (URI(CONCAT("https://some-og/datasets/data/" ,fun:CSV(?entity, "animalID" ))) AS ?animalIRI)
}
`

**Comment by maximelefrancois86** [comment]
See [working example](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCOSrjjDm5eARExcVlZAHEyADkyBSIAFUpgaRkKAznWBZ4+RuYYGS0RhGZgAH4Hp5gEVQARAF9JDAKDNPs8KABuWTnGEg9i4GTcCAUN6IrjI2T-WSqI77A4AeQU2l0GFwAGESAA1AAUsSMV04N2Wonuj2eQgcADdxAAaChIDDoPlSEBSMWikDCyUiqVimQy6QgMHfP4KkVoiAigCUFFIKOVP1+KI1sgA6gAJPbHaGnf6SkAasBoTBaCAOPAAbQAujzwNB4MhbNkGDQ8CB7Y6gzAQ+7cN7fWBhII4OiZEgHBAkJ7QHAMFow1V5oylkIWQaOZz7Q4BVoZLYwwa-jyTTJ2i0eTBZK0eWBZGZ21B7eiwFo-FgGBAw7p2EhmIIuSB-j6QNWMBBuHhYAgM76EMJbHxORAEHgAKz-IA)

**Comment by nimonika** [comment]
> See [working example](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZRRUNCig4GX1aeiZWc0trO0dnVw8vHww-CGYoGWD5JTVNdgcwGMN40xMTfnNk+wAmAAYWgEZmdQBZABkSQRoILhgAYkkQ4vCOSrjjDm5eARExcVlZAHEyADkyBSIAFUpgaRkKAznWBZ4+RuYYGS0RhGZgAH4Hp5gEVQARAF9JDAKDNPs8KABuWTnGEg9i4GTcCAUN6IrjI2T-WSqI77A4AeQU2l0GFwAGESAA1AAUsSMV04N2Wonuj2eQgcADdxAAaChIDDoPlSEBSMWikDCyUiqVimQy6QgMHfP4KkVoiAigCUFFIKOVP1+KI1sgA6gAJPbHaGnf6SkAasBoTBaCAOPAAbQAujzwNB4MhbNkGDQ8CB7Y6gzAQ+7cN7fWBhII4OiZEgHBAkJ7QHAMFow1V5oylkIWQaOZz7Q4BVoZLYwwa-jyTTJ2i0eTBZK0eWBZGZ21B7eiwFo-FgGBAw7p2EhmIIuSB-j6QNWMBBuHhYAgM76EMJbHxORAEHgAKz-IA)

What is wrong with the query I have provided?

**Comment by Antoine-Zimmermann** [comment]
Monika,

The function you are using, fun:CSV, was used in a previous version of SPARQL Generate because the CSV iterator was very limited. Now, the new CSV iterator supercedes the CSV function because it can assign any number of columns to multiple variables in a single line, as shown by Maxime's working example.

**Comment by Antoine-Zimmermann** [comment]
fun:CSV was silently deprecated, then completely removed, as a result of the evolution of iter:CSV.  Granted, we should keep better documentation of the changes between versions.

**Comment by nimonika** [comment]
> Monika,
> 
> The function you are using, fun:CSV, was used in a previous version of SPARQL Generate because the CSV iterator was very limited. Now, the new CSV iterator supercedes the CSV function because it can assign any number of columns to multiple variables in a single line, as shown by Maxime's working example.
Super. That worked!!

**Comment by nimonika** [comment]
@Antoine-Zimmermann Thanks. That worked!
