### ISSUE TITLE
Version 2.0 is far slower than version 1.1

### ISSUE THREAD

**Issue by jm-gimenez-garcia** [sparql-generate/sparql-generate#72]
Version 2.0 of sparql-generate is far slower than version 1.1. This specially impacts when using json files as the source.

A couple of examples:

- Json file of 528 KB:
-- v1.1: 3 seconds
-- v2.0: 50 seconds

- Json file of 1.1 MB:
-- v1.1: 6 seconds
-- v2.0: It never finishes (I stopped it after 2 days running)

**Comment by maximelefrancois86** [comment]
Hi José, 

Can you send me these files to profile the code ? I don't have the same issues.

**Comment by jm-gimenez-garcia** [comment]
Already did :-)

**Comment by maximelefrancois86** [comment]
Solved in current version
