### ISSUE TITLE
Example of Sparql Generate as Maven dependency

### ISSUE THREAD

**Issue by Pat-Carroll** [sparql-generate/sparql-generate#73]
Hello, I hope this is the appropriate place for this question.

I have seen from the website documentation that Sparql Genereate Jena can be use as a library imported via Maven dependency or built from source using Jitpack. Are there any exemplary code projects available which show a minimal implementation?

In addition, are there plans to bring the 2.0 version to Maven central as well, or is the preferred method for future version to only offer the dependency through Jitpack?

**Comment by maximelefrancois86** [comment]
Hello, 

SPARQL-Generate 2.x is now on Maven central.

See https://ci.mines-stetienne.fr/sparql-generate/get-started.html
