### ISSUE TITLE
loading JSON via content negation fails

### ISSUE THREAD

**Issue by mathib** [sparql-generate/sparql-generate#74]
Hi Maxime,

I just played a bit in the online playground, but I found that I couldn’t start generating the RDF as I could not retrieve the JSON. The JSON is available on <https://id.erfgoed.net/themas/9424> via content negotiation (default is HTML), which I successfully tested in Postman (GET request with Accept header set to application/json). I started from https://ci.mines-stetienne.fr/sparql-generate/playground.html#ex=example/generate/00-Source and added an ACCEPT header. I could not find a list with expected “type_uri” entries in the SPARQL-generate documentation for JSON, so I tested it with <http://www.iana.org/assignments/media-types/application/json> and <https://www.iana.org/assignments/media-types/application/json>. In the first case I just get the HTML and in the second case I receive the following error:
```
ERROR 10:37:33,490 - session-1551-1:RootPlanBase:288 - Error while executing the SPARQL-Generate query
 java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: this (class org.apache.jena.graph.Node_URI) is not a variable node
...
```

Used query:
```
GENERATE {
  <s> <p> ?source .
}
SOURCE <https://id.erfgoed.net/themas/9424> ACCEPT <http://www.iana.org/assignments/media-types/application/json> AS ?source
```

**Comment by maximelefrancois86** [comment]
Apparently the Accept header wasn't re-written for the next HTTP request following a redirection
