### ISSUE TITLE
unable to download dependency 

### ISSUE THREAD

**Issue by BitastaB** [sparql-generate/sparql-generate#79]
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>

<dependency>
    <groupId>fr.emse.ci</groupId>
    <artifactId>sparql-generate</artifactId>
    <version>2.0-SNAPSHOT</version>
</dependency>

I have included them in my pom but it's not able to download the jar 
Failure to find fr.emse.ci:sparql-generate:jar:2.0-SNAPSHOT in https://repository.apache.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of apache-repo-snapshots has elapsed or updates are forced ->

**Comment by maximelefrancois86** [comment]
Please note that v 2.0 should be reslease in approx 2 weeks on maven central.

Also, some of the API changed, so the javadoc online is outdated.

In the meantime, you can install and work with the snapshot versions as follows:

```
git clone https://github.com/sparql-generate/sparql-generate.git
cd sparql-generate
cd sparql-generate-parent
mvn install -Pskip
```

this will build and install the jars in the `.m2` directory, then you'll be able to use them as a dependency in your projects

**Comment by BitastaB** [comment]
Is there any older stable version that I can directly download from pom?

**Comment by maximelefrancois86** [comment]
Yes https://mvnrepository.com/artifact/com.github.thesmartenergy/sparql-generate-jena

**Comment by BitastaB** [comment]
Thank you :)
