### ISSUE TITLE
--output option is rejected as ambiguous

### ISSUE THREAD

**Issue by darkling** [sparql-generate/sparql-generate#85]
Version 2.0.0

The `--output` option to the command line tool is also a prefix of `--output-format` and `--output-append`, and is treated as ambiguous by the command-line options parser. This causes an error, and the tool does not execute.

The `-o` option still works, so there's a workaround, but it's unexpected behaviour.

**Comment by maximelefrancois86** [comment]
This issue is solved by #90, and should be part of version 2.0.1
