### ISSUE TITLE
No output to disk from command-line tool

### ISSUE THREAD

**Issue by darkling** [sparql-generate/sparql-generate#86]
Version 2.0.0

The command line tool does not seem to write output to disk. I have tried both with and without the `-o` option.

I'm invoking with the following options:

```java -jar sparql-generate-2.0.0.jar \
     --query-file "${binding}" \
     -of TTL \
     -o foo.ttl
```

The triples are logged, and then the expected Turtle output is logged, but no Turtle file is written.

**Comment by maximelefrancois86** [comment]
This issue is solved by #89, and should be part of version 2.0.1
