### ISSUE TITLE
Nested aggregators

### ISSUE THREAD

**Issue by luigi-asprino** [sparql-generate/sparql-generate#94]
Hi,

I would like to compute the average number of objects within  a category.
Suppose to have this [file](https://gist.githubusercontent.com/luigi-asprino/3a68926e231e9395243a490a3c1617e6/raw/55996f5dfa0d1501e6443d7e6d52665cd9ce501f/test.json) where cat is the category label and id is the identifier of the objects.

I can easily compute the number of objects for each category as follows

```
PREFIX ite: <http://w3id.org/sparql-generate/iter/>
SELECT  ?cat (count(DISTINCT ?id) AS ?numberOfObjects)
ITERATOR ite:JSONPath(<https://gist.githubusercontent.com/luigi-asprino/3a68926e231e9395243a490a3c1617e6/raw/55996f5dfa0d1501e6443d7e6d52665cd9ce501f/test.json>,"$[*]","$.id","$.cat") AS ?obj ?id ?cat
WHERE{

} GROUP BY ?cat
```

Now, in order to compute the average of the ?numberOfObjects I was trying something like this:

```
PREFIX ite: <http://w3id.org/sparql-generate/iter/>

SELECT (AVG(?numberOfObjects) AS ?avg ) 

WHERE {
  {  
      SELECT  ?cat (count(DISTINCT ?id) AS ?numberOfObjects)
      ITERATOR ite:JSONPath(<https://gist.githubusercontent.com/luigi-asprino/3a68926e231e9395243a490a3c1617e6/raw/55996f5dfa0d1501e6443d7e6d52665cd9ce501f/test.json>,"$[*]","$.id","$.cat") AS ?obj ?id ?cat
      WHERE{

      } GROUP BY ?cat
   }
}
```
But it is not syntactically correct since the ITERATOR is not in a valid position.
So, I moved out the ITERATOR clause 

```
PREFIX ite: <http://w3id.org/sparql-generate/iter/>

SELECT (AVG(?numberOfObjects) AS ?avg ) 
ITERATOR ite:JSONPath(<https://gist.githubusercontent.com/luigi-asprino/3a68926e231e9395243a490a3c1617e6/raw/55996f5dfa0d1501e6443d7e6d52665cd9ce501f/test.json>,"$[*]","$.id","$.cat") AS ?obj ?id ?cat
WHERE {
  {  
      SELECT  ?cat (count(DISTINCT ?id) AS ?numberOfObjects)
      WHERE{

      } GROUP BY ?cat
   }
}

```
But it doesn’t work, since the result is 0.0.
What am I doing wrong?

**Comment by maximelefrancois86** [comment]
Hello Luigi, 

If I understand well "id" represents a number of elements ? 
Then, does [this query](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAlkhLjQDwAWSSADrgPS8B3AMx0wAOgD2GAOa8AzlxgYUCALTSIAO0wxGvBpl4A+ADqaAyiQAyJAMIAVGjQD8AY100AFK4lxNSTwARCnN7CgA5BxdRAEoaAEFzF004AFsAI0wAeSgs9IArCFckOTjPGAA3aU9nWISk50rpWLMKexIiePssonpGXAApcyzwgl02T3ZOLjk+Xma5JDFmpDY4dLg5TB9-LSWfVN4EODpm1RgFDDpNCV4hGAA2AA4ATgAmB4g3oQBGCBehC8AKxvAAs91BLwADDAhK4fg8fgB2CAPXgYGACXhAoEvF4PKBAsCwKFgH5AqF-B6g8FgFEPMAgh4PIGuMAvVwQCk-KC8RiLMT5OQSTRGAA0JhAABIANoAKgAupKJdKxKJlZKpWJ3EhJXFEi4JAVomAXDqzAB1AASHRIwDMZgAvjQAOJELIAVQINAAQgBNM26EBikCaGCpCBgNCYOgQOR4GUKkOQWCIJDSDFcNh4EAAAXSFwgTmLJdYHG4cwgAA9w1wEBBJDJjDQxCYMGZc1wMNA6FWaBoJMwnFMK-wBOOxMJG7I3lCoUJeJT5hBbgJpHInqCAPpcCRyADERhbbY7XZ7farcjAQ7L0zm44Ek6E094s6XVAAslZzK42BBUjAh7Hu2midt2UC9n0mBDiOPBjiI4hSLIChKCo6haDoegGBgzatiBYHnjQGDErMw7lnBggTlOSGvnOUKLj86LEqoci-v+gFHnhp7gZBMAoHQg5kdMsz8K4dBiKk1xxixjBILGmjaGIUA4XxdC8CKSASAgEjSFgQFcaBZ4QX2UB+DesH3ghL4ocoagaNoGJ6FAmi4Sehk8X2chyJo5nkXMXBwBgCCSK4CCuC+4QkPY8jeVWMWaPpbkEcZNDCnIMAwX5Y5Uc+NGaHI8h7jArkgW5sEibwYkSVJcgyRAclaIpym8KpvBgLoxXaa4i6mCBpbFjA-VDWlGVkBAuiBRAOQULs3aLDQADcblDURJG4AgMCZAgJaSj6ShXBAYo0Fk-hKAJkqLctQ3EVAsxbBA8QIMKQmji1-GuJoL5iUgWCVTAYbtepp1XLcBYYAdzZLX1Q0DutHj9TSYhCE83yIpd0P9bD2maNI-WqEiLxiEiULfFCDzAQ6IHlXMVWSdotWLPV8lNSp-FtR1i7qekWwYBUugCflvDkm8SLkg8dH7qpvVmCtg0rfLsv8YO8R0BgACKcAwAgDBYDNkBVnkPN83JIrozLw1FbgbAXGNE3dtNs1xkgL0zDT4l09JjMNQpDbNa17VIJ1EjdVCR5Q+b-UjVbFzmHQqR1hARBxmmQ1AkIZuaCtUdGkbkYEBgEhcJgP39dTonuzVdXeyzb1qQHQch5L-Fh1dkeW3Nab2HHRYKzQkqzj8TyqFCQKqGC9g-FCuBztPULD0Cs+SgAekvl7XgHEBdxGFOaGV5EVbTlde8zvus3XHNdbR0uZ0Ncu91HttIJNDuMHNzvhzf-U3bMG1bTtIBZBgAAawqHQBA9YjonUDiDC6H8Vrf1wPdR6z1byvVUh9L6Os-oA2KhpM6twJDANAeAiAkNW6lixvDUs4IxCgieA8F4yIM4rSxiKXGpZ8aE2Jm8EWTwd572Em7aq9Mq4nyUmfdmgcjjB0XE3Og19Za936qpZWqsNZax1nras+dC7FywMw4a3lcB0DkDoouGAfo5BdgfCuIjj6NVPrXSRDcer8KpvvIRHsGayTEX7Nm9daJcyNvzEUBVhaiyBOLOcciFG3yUfEmgKjcAq3VprbWP0tEG25pgY2AsDFt3StHOQj9n5QBmq-J21jPFHx8Q48RTiAmX1nC3DGpYo7WzkLHeO9Yk5yBTv1Ck+S2mWxzjkvOBdzEl1LGXSqtjPa1J9vU-2F8ZGzhiUMksUcO7IC3j3BW-dKRDxHmPUEE8p4zznPPReIAV5r1wBvXZbizAzMPnYhZNdllSKaVCGJ5CSx3wSUklJ6j0m600PrMxeiNnFi8j5ExkKLFYCsag125dhHzKZnUvx58vmrNDjvHa7jBFoq8aIrFEjGkyKEKHP5A14kP3Gk-e2ZTHbzTgddNav8IDbWLJKcwSwaC2HGGdemkDgbnRANCpwCCkFPQkC7OY6DPo0W+r9dwOCgbQIEvIJYqgdTWyuPTMhrSSyUOdgjZ8CI5yRKlf2Fc602F4wJmIb4oIkRAieZoF5czvGYsWdi5xdx6KjN5iEwW4SxYSylrSpwAKEmKwEsktRaTNHgurIbHJYbbXtJtoy0p5TMCVJRTY9Fvrq6OM+S46lLSI7DMKR0rpCden9NLEIUE2aRnZN5uM3RiLS4eJJTUv1Hz-ErO6tS9Z7KCkZW2UgR5vcDmD3nics5s9Z5XLnMvVeV57m6E3t3T13rS1kv9RSsdQbfkmrpfGxJSsk2pI0RktNVYEUlynW0ox8KJl6ORUe0l9jT0NPPdWw9A7ZnHoAyOnFxVQTBq7bk0JQsQSi1BCCaJ0ar2xpvQrIFybH1gv1hm0NJtM7vs2ZbDpJTmUFrflUwdbzh0VtHbi7qsGa2fzrRlBtccm3J2QENH47ayMws7bnMAr79HTLA68jF5alnMZcbBydMbUrtz43Og9C6QADyOaPceUIkRrsuSPa5tyd0PIPQZAR3AS3-veUx6D0jWM0sw4k+llsqNTRZRUtlKmEFcp5U4SUM04CgKAUdcIUhVgWidvYTAVxNIHTkLAvza1ZUoIsvwJVmCfrYJgIDG4Fi2ACCdq-BLUhYwFWuKFugQDjW1tNfaja5rSzPCRpEvEQmVOsJxnjH4QhnwobJunKzRKbPVIY3JgNlLnOXoa9e+NuGH2gsyRJ7Nn7THfsRb+6TPqT1QcDZfNjoHiXgbs4x+TjnL4Ulico9zhTPMv0Lb51z-nNrcv-uYf6NAxjpG0il17aWIAPTlQqrL71lVNlVX9bWUApCaDoMVHwFwkDnHBXqvYGI1AFl+ulTQqhFB-duOxlhTWqEliEEiMQ+IoRddcz19hJZVA-B4e154J3xv0dk74s9UiKRBMzSRsJyH+tPCjc3FTcbsP-LvcClNT7CPwazcJpwObil5uo6y81f6h1Td5y4m7Hb60xx4z09TQ03gepV6pwpIaKg9smZJksOvJs86Ayx7EPypZG5nep+d+ztOHOXfpheFy55QieKZ7d6892PNG883bEH7OXcOzIikc2OP-Ow0tkFqaIVbbfSp2FxjNu9ssVAOjZ3ddu8rU5z3nE3LWdRVX135L3fFXFgL4jAthcfA62+DPijpe31l3hlbz6iMIdI0Xijua7ZeZo0Wl33O2+18vuLEnFtbfwYd1CqTp2ZNlprwpuv4tlOua2X7zTAedPLuRBPUP5zw+gij3ciz2949esT+dvX7fT9e4l1cyl17hz3lwI20QL30Wt2Ly-TLyRQr2LQmxX0AzXxkQ3w52b0P32wc1T26g30l3u1Gg1wXy11tTez-l5RABowjDAER0YBoB-DYAkC0hoCRFBAiwgAEBoD9CkCAQB3m2lSBxBwyyylrgwRVSwU2GKm0AECwF4P0FqjYPq0z2LDNSGlgzECeHJCBCYWtwZydWfCeCeBxBBAwNs2r1XxP0vmJlu1LGAOnVwEe282e3flS1ujhgoKCxAB9HGntwsRFEgW7GkBFH4JUMEPcPS3lRRUVQhxy1+ikPUiCJFF4EyEqGLmSM30xjJxaxLFQ1oW4VtX0I4RZzeE0PJBeDMKQKP0sMc2Ji7yn171FjbVgwAPkQIOH2UVH2Wzz3TSVxIx9yKScMX3mkQK52qJQKsJkRsIGO426UTnN36kHgGLt13z7X305xb2QIOxm14GJnPwEJt19z6R2Wv3lkXV0xXVpyM3D0M03RuWj13UYDj0bzG0wL20gxwJ2L2IwwOPsPllAPw1W0gPWzhVL0dx2wP3eOT2m3PWmM-2X3GO2PPTF0HziRvQBPH3zzgJBJLwkwhI2KwI+JTx2LFwb1KlePMNbwmKuxkVJPaPvg82IKe1o2t3II+0oIAGkNoAJVgaAyAtYnpAiIBgjd5JVWShDkEojMsxDIdZBocEipBhTkigFuTxhVBYBwECpMiKFsj1DSifhoQ3h8RCimtHVii3gfgiZfghAGFKixjsDiSOYxd6iw1GjRdxc2igCOjOjE05dASJ8+i8loDZ91d59mSl9v8LDqTcDeBSSZiTc5jm1+N+o3g+Fgzt8xM1t1i3ik8LsYSPcUTvd0yjjO5TiVpzjg9TkTMw9h5bioQt039Y9LMXiE9ITczf9UDupoRbCs8lEGUwznCWS3Cf53tAs+4QBzBrYwB9FbAJB7chSRTQj4EJTQdojwc6BxCodJD0pEilSXI5ApysA9U5zSFtTGtBxms9SxAHhvgeErdutTTetzTSitDKQgQ+FP8m9KStjPiOZoQXShckMRZBMrVWieyFtvTY0ujc8Fdejgl+jizBimTByIy2yf9j8aSuz8VELZjeNjicjix+tlid9xNgTszvzETfyPdoR9iwjDjcBZ1-czjA8l1jl9MHhrjazX9zMmyP8Wyv80KoykTqKwL6TAVoKwCgTsToCNs8SECESHT8yXFuy7TNjKLHSPdJ4XNfjCDHDkLhjXDAd3CAt-4fCSEKh0AaALQYAsAjozL6wLLDorKLg2BrhpBNJRSyCVyRC7x1zNy5TtzioBAXK3KPKUjuUHL0BwrzL0BVBgrfozzVDdSEYqdERfgfgTSLyzSmcSiXVKQ0Z4TIyqThLiotKAKe8hZIRQRngWjRKvTIKBoJL-TFd4KgyZ9jdQymUSCfNtciqfyNKXEtLErVcQzG0zd8KLcKjEKVjSLsTyKqjFL9c68tLaKs41N8KmLyyWKkQ78hAJ4X8ayDNuKY8njmzyTWyCSoS8ylrL4Vqfi6K-iE1VFujYKX1gSZLQS5LK9CToSbqZEhrVKfrrq-9brJ5wKsM+zGSByDKvLjLRz-4LQaAPwYBrgGCkAjpAgbKPKjprKDzQqQixThzEFgdJSwcZS4jeAEjgq8acYwr2osAwqBBVAAJrgZJlDScLzydixqqkYli9DHzGdixmdkRqdjDAarqOyT8fhJ5yrEMI1kYPTwa3MGqoLfSx8eislWrTYcK58urwyRiFKiSlLlqwb4zOlTd5iJqUy6cDjs4SKsznc+r1LjbQawKBjGKyyhoKy2KqzH910jq7izMTr90+LzqBLLr2yMKYzpa6qdL0SmrMSIDpKi9ZLID8Scz0Kajo7TbCrBLiqqLBrmkxL5Z+y9aUKXsDi2SxzJRqVeT4h5yaArA2FQFOCcaQraaCbYa7oSbVzpTssJDcsqb273LkjsZpAW6sRa62Bzh7d2aYZkrqEHgxB+sXgaR05+asqnycrWd8QDSaRxbI6s6AkWc4Mtbw0RcFb0NAC46VaMSNbJ9ld2quNdb81SDRi1LFqQb-rmkzaxrLaW0Sw0yn7cAZqHbixDbfqv7uoT7Vqt8SyTjt4tNb8fb7Bqyn8uLA6Hj38ixc6I7M7oydiYH7qh9FsE6Na1sPrcS075KnbP7OyhYf7cGM6hKC7lrq1i61qHt9LSDxS4bPDxzbA-xrZtY5AaB7ArhMhIEiEwEIFnKaaR7PLeHu7hCpTRD+6tzB6dzqbXKO6XJCEQEZHSE2JhGTFVAkAJHTzMq4YCKnAeatCUZ3grGx6+tvhl6XhiYngRt+KIHgb6H+tY6Hrs8yHXqKGU7PrqHvqJao7CGQMmGKK6GpbqVZbw06EoRgQkQB9iG0Tb7gnwDNbBc2qL8Qyhi36fHJbMKhYQMdbzbEyFjSxyRiLMyyLHa87+qXb-qJ0izgGPbEGb98rmc3h54J46z-a6yGyeLTrQ6zBgxQxwxIwMwYAsx4xcBExkxg40g9gtgkAEwkwQBFhuxww8ANStgQxtJpAHLuU8AgRHQgA) work for you ?

```
PREFIX ite: <http://w3id.org/sparql-generate/iter/>
SELECT  ?cat (count(DISTINCT ?id) AS ?numberOfObjects) (avg(?id) AS ?avgid)
ITERATOR ite:JSONPath(<https://gist.githubusercontent.com/luigi-asprino/3a68926e231e9395243a490a3c1617e6/raw/55996f5dfa0d1501e6443d7e6d52665cd9ce501f/test.json>,"$[*]","$.id","$.cat") AS ?obj ?id ?cat
WHERE{

} GROUP BY ?cat
```

It returns 

```
----------------------------------
| cat  | numberOfObjects | avgid |
==================================
| "c2" | 1               | 3.0   |
| "c3" | 1               | 4.0   |
| "c1" | 2               | 1.5   |
----------------------------------
```

**Comment by luigi-asprino** [comment]
Hi,
No, sorry for the poor communication from my side.
The ID represents the identifier of an element.
For example

```
 {"id":1,"cat":"c1"}
```
This is the element with id 1, and it belongs to the category "c1".
Therefore C1 has 2 elements, C2 has 1, C3 has 1.
The result that I would like to get is that there are 1.33333 elements per category on average.
In SPARQL I would do a nested query, in the inner query would count the number of element per each category and the outer would average the counts.

**Comment by maximelefrancois86** [comment]
Then this does what you need: 

https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QAKASgKIBiAkgBoAEAlkhLjQDwAWSSADrgPS8B3AMx0wAOgD2GAOa8AzlxgYUCALTSIAO0wxGvBpl4A+ADqazAZRIAZEgGEAKjRoAKGADdpLgPya4AWwAjTAB5KBDAgCsIAGMkOQBKGgBBCxpvDx0NBLMKBxIiZIcQolYObj5eCAAPGH8uBAhJGV4YiXq4RmT3LIgjFyTU9JjddL8g0PCo2PizAHUACQKSYDMzAF8QABoQTTqIMDRMOgg5PABtUDgMOjwQcp5+GrqGpqlZNo6unowYDW2QP4DnRdFguBA7jAuA06CMkHQJJpeO5NOIFEoVOotDpGAC5EgbpppHdiORqPRGMx2JxHoIROJ3vJFMo1BptL89AYMMY1porLZHM5vHDXG04JokC4ACIUCwOCgAOUF3lEgzSvgCwQwYQi0TiiVy+UKxVKBlwACkLCEFQRdGwXNTuHJKtI6PixK6kGw4IE4HJMG0JVokGJPrwEHA6K7VDAFISJLwhDAAGwADgAnAAmZMQTNCACMEHTQnTAFZMwAWJMV9MABhgQhi+eT+YA7BBk7xfgJeKXS+n08moKWwLBa2B86Xa4XkxWq2B28mwOXk8nSzEwOmYhAp-moLxGO7InJEUYtiYQAASc4AKgAuhfz1exKJHxfL6HdBe1ekJFF0qIwxfpoizLKs5iaOsNAAOJECEACqBA0AAQgAmkBSAgOsd47JAsCIEg0i-FwbB3AAAoEsYQM4NG0WUNKVM89SNM0shGDQYgmBgZhkVwGDQHQ1Q0BoEjMM4jq0gIUliMIrG8Jmta1kIvDTrwImCNIciphWAD6XASHIADE7Gcdxmi8fxUCCTQ1RyGAYn0RU-BSQIMlCHJCmqVQACy1gWDEbAQP4MDGRxXE8XxAlCVyYkSZUwiiHJ6Isli7K6BA+iMNyJnheZkVWUJGCjs64kPPF0myYynm1ip+ZdqOqhyAFQUhTlZkWVFNAwCgCKxQ8zr8DEdBiP4dDaHIjWMPCWjaGIUDct1dC8IiSASAgEjSFgoWmRFlnWVA4oOXFzn0klzKYmyOIZVASJtbtnVyHImhHWV-BcNcCCSDECAxHJCokA48hPdUQOaNtuUdQVNAnnIMB9QxzkVe5jKaHI8gGTAxhhWZuUSQNrTDaN42TRA02aLN828ItvBgLomPrTEKmmGZdE0TArMczDcNkBAujXBAYQUEG-H4jQADcuUczQRVQM6CAwMECC0ReyFKDcEBbDQIQSkoCIXuLksczLzr+hAyQICepUI1TPUxJoclDUgWCtDAey08tOs3AmlEYOrWMSyzHMibg8tIBzc5iEIqZ5i2BuB6zwfrUSrOqK26ZiK2tZ5rWybY2sZl45UQ0jWNpwk2TFMLT1NN0ypy2BP6GDuLoCKo7wk6Zq2k7JoptaGYtzNmFL7NS6Pw89aJyR0BgACKcAwAgDBYELkDVBEjfN-CiJx0PnMY7gbCxjzfP8YLwunGHjlcPjxdE2X+Kkyc5NNJT1O00g9MSIztbsQHu+s1zA+sYLB0GYhAIgpwCIc1LEIHemgpaAL-BvA4BAMASHBBgJ2rNC6DUJqXCaD8K4vyrktd+n9v79x6r-Q2AD94iwIg4UB1Ex40AvApfMqZVC1lLKoSsDh8y1lwIpIRtYuGlhEReAAepI2y9l34QEYUCPO5gC79SLng4mhCn6VxtqQ2uDN5I-xoXREeLDAHHyQPzM+WUL5wKlsbEOCsIBKxoheEIMAADW7g6AIEaJrbWH8vb6z-vAo2xVcCm3NpbK+lRFp2wdkvF2btMYrV1gmCQnjvG+IytQ+OdFE6jFZlWMQFZUzJnTG2OxQcICiSTtIFOacM5Z07qmZRuM1G4JLpoqa2jiG6Jrh-cMX8VKULoIPUJrNTEsLZhPXAU9Z7z0Xk7FeNRUHoMwFgkJCCnq4DdGsjBTswhWydOorp98ekzT6W-fRwyf5tNUTSG+GjzmP0uXNEhAzMYKXrhvFuiI0Ydy7qWHuilRnjOHtMyFXVZnzLngvJeKy14N0wJvVuVTaGwyAXICxVioBCxsaLK+TyzkEIuc-d5-SyFDMZgpXJ-86KAMPnIEBYCIFyCgazKc6KGX7yQSilBaCDlYGwR0gmJLy69IpdcwZBiFJgu5bRQB9DkCKOYWPNh05OHcN4RWfhgjhGKTERIkA0jZG4Hkaq+5ZgcFirvqS155LX7VypbKvuA9jG0SmZCxak9p5wqWcvVEqzBUbOFVszmOy9khswVgI5RLTl2olW8p1eiZXDNpco5WDyTmdMTVo5NHyXXDKEEYvJnrIXmN5pY0+eLz6i3DazBx8tFbKxABYEMNA7B2l1uNfxns9YgAVTRBxkSLYSGObSOJ9tGSO2diMZJHtAkInkCGVQcJD6ElOP7D1NECmXzosU5silgVDucInRE9S6Kp3TnmCsrZSxWs0Da2++Ck2OsLbXEtPyUV-LboC7uvcwU7ucF6qFHMfVzL9YshFQakW-K3vAhtPLMVMpxTW-FmBbHxtza+-N77KU3MZiWulEzkNwyZSy14bKOV0SEBWU90NeXIqbgK9ZMaRWPITbhslOjpXkMTG6qhDGlWQJVUw6ZGqOFiJ1XqkRIijWKSkTIuy5r0qWp2io61oqX3dIdbx51hGBNAbLWzMDIGYVQfhcs2D+zQ3CcjXIWzMa43PuefaohUqDNpqI3cjT7TOM4d0x5lNnzeAVhqnypuv6AXli7hWcsoL3UmZA2ZseEHYXQes6vdeP6EPCf3qhqtuKMMi0vq58VeH9Opv4+FkjCCCvANAVR0T+7aL5no0hxVTHkFgCc1gui5W808auV5mrgmxn5cxcqpAlqWGSa1TwvhtZWxycNdw41pqVMWvE357N18uNBclSFotjNavAa6hW-eaGBa1oJWHTrw7wnNuca2oWcBvEeM1gqKQXo5gXwcJgG4q11ZyGCedkdEAzZjonbE2206WizqSTAd2mgftsAEBfLKQOpAnDRmNd7dAPHbuS8JGpjjWs0TTJHYFA4OvnfPcnK9+YhDuTiznWBu2tMBdtdxvTI3qvUrC+N8F4HUvpcswGxFfWw3nces9KNbHDlQAncSobfPPMC4MbVx9g3efBY-d53spb6XlumZWk+N2Su2Ie84JtTiXHOAvBYV2NBbSBHWmDknEOofROOro+JM7EkjEXlAKQmgQStAyfiGMqI13Bl+GoSiztYaaFUIod3CY6vVNqYU2jrYxCDlrHTknDPL20VUPmTMmZqdph19ptzb6quhanN+qLCGYud2Z6mQDSWTemdS+PXqGWrOBuy8x1F28beMZQ0fIr6G61lfrxV4bGvQsGKnFnjF5HGuspaxzTMD6p+IPH6xoVHGc088OwWgjhupzyqP3Qlrs31UgHYQtmT62DWiNrKmDbym5FqY7a5T+YX46YvL64378Z3696kam5gbi4LIj5S7RqbKy4ObS4uZL5q4QF8aC4b517c5gHuZHYG6Yw9yt4T5-org06eTGZ94pYD7gYWaIGS6wY5Zt5ooP4z7Ypz6W4L4q4HbgEkGQGC49yb5ka4CRY9C9YoHCoDZYF67CG4EGI9z36y6P7spiZKJzav6arSZtj8LiJf5cIVh-5mrbZKKc5PoKFX74bKHDKqEwEQpmYIH+owarzS72by6OayGYGEEN6Vb85r4OG+bAF7aq6KHX72GMxiHnagZ7yYrXbWKYb1rg5Pb26vbCxAhgAgiMA0D+RsASBrQ0CtgVhfYQACA0CoRSAeKe70HSzhKjq+6vT+7w4fCJJ+iYzaACBYA1H6ATSlHE71F7rhy1hiCpiTiliVJT6l4NLuSpiph9jlgEGgEBEr7HaGaZwi6TKXaJG8HJGlYMZ24tquIgDIS8w-CrSaD+L8TSCIh1GwGPaywRKQ5RLjoxL8BToJJOy8CdHLS3GIi8DBCZCYKAniG0QjFFKlglKZyZgMazFM5V7jGTjpgrH7aBZCFRGja8CZwUHRbtyxbM5ziJZUJxGMFMFD4S7uE1DsGUGTbb48EW4HFYa662FN4nY4l3JcEMmUaNDUbIAcwcL0mSEn4yGK5yG0SsmYl2HYkGKZxqEk4iaaEzbiY6Fv7SZLamHGHLZmFbaAGWFhFc6rHL7q4bGG7ylOGi4uHMFuFZbBrileG7I+Hil+HGnYFKGynDJbFokRFslBEcnd50GPEMHwE2mZaj72ln5H7oG+HK7YaX7SnsmGbd53SabWH+Emk4GemMwplklm5Xb7G3YpH3ZpHPHPYO6sIgAADS8swUXoNAZAC8FsNxEAdx5gg6U+3ubxMOnxcO3xzsfxUgrZgJHitZdoqgsAviaM4Ju6ZOoc4c1e+YdYmYg48Jc5F6Kcle+YGcBYQg5SPpghxBWJAu3eeJ7eBJneUcPepJJO8RjBrh4ZiKtJv6wphWTJRZhx8ZRBje-pyZXJ6h3BvJ4Ce+rMmYrS3JIpPWnh8hGZ7px5wROZwuwp02z+o882Gpuqn++q3+K2imJq-+qmjA6mhp6ZbpkRMpmuwydY2xJiux3MhZVuqRXu6RJxjubah8YAwqdgEgPQLZbZDx9ijRrx0OHxrR-ZvxsM-xw5SIcgHFWAa6PFOSa5OeFOzgFY1eyYeYVeh+9O65jO5ele1eEx04pYrSVhIB6JCZR5FFoWdYZ5rcHecWR6wueZ5JnqYZSBbB4+L5EFb51afBd2AhGJ1lSZhu1Fr5O+zWypgpsCEFUhp+dmMFZFfpq+HJdYCp9RSpDCqpL+6p2qS2yYq2OFupABRFQBOM4Rh5P5qVhm6VlpOx1plJLB1J1Qnh0Z3hGBcZUpIVv5YVoRFVRpll35gRNVhuAixuwZF2+Zex75jFJZzFZZGRpx5x2S7g6ANAcwMAWAmsK1jQa1GsG1sYbAY00gVxAlYSzxTR7xfuXxgePxfxAgR1J1VxQJzie16Ar1q16Aqgj1zsM5Z6c5uetEd6YgLYBY+YylIcG5iJ1e7CscVh3V1VZpmM419l-y7cNYFYaY4WJJYyrlbl5mTVtpEZcGuWnBAFDJSRH5LJNhiZvV-G41-10+PJTWfJIFdEK5wp8VYpZ+SVQ1axpppBgu41GVk1WVWhaqaFuhbY+hQg-CWp2FXCuFtYSm5h+p1ECNtNPVo1DNuNNFcBUKD5nlHhshjpCuQqrp-NmZHplFjMjNB5wVSNQtBi+YAi+t-eZiBZs1-BnZLFL2pxcwNA3kMAY0+RSAmsUoW1Vxmsm1slz19xHZpZJswlzR1st1COHRklj1cdRIL1tMWAL1AgqgwUY0k0Qxk1kJB6yYkcQpMxelZeNEFebYBeixDtVlTtIhrtEW3l55-6V5et+NBNRtrBY+8G5NipDWjJ-lzJhKiNI1yNwtbtEVzKrNwF0VoFxemV3W-KPNiVkpWtHd0R7cAiot9WU2T+OVUteVi2mFRhitOpeFm2pVCi5V+cg1vpdNOti9Llt5YuHlI9kZdm7VTpnVQV7d89ztwyXdqZFlH92tC9LttKg9Z99F3tgVvti1rFlZJa9Z3QB11gF63iFRMdT1udCdRxQlPu11LR6d7R91WdpDp1gJdSRDPYODbAMYPQ5dUsldwN1dzO6Yc4sVultS0NBlSJg4S5c4bdw16xQtle3dY96Nfd3eA9v9BNMyRNj5XlSjiGFNWKVNc1YDsjgtIhiD-5E9gFq9-JqlNA4F+j3N0F+9sF5FoVDNcqA8yFF92huVeh+Vt9RVStJVhFL9BpA1pFVtcFNlHJCjQZzhoZWjxtgD7GwD5toaltcDh92Z7cGamtLjKVCDUDxGyDCRqD091NTF9Rxx-tbFdggUh8i8cgNADgNwwQ-imSPifih1OdTD7ZFDl1Kd1DadfZd1A5DDPTL1GSXinTGUzUDTboqgBIdAwQ3D2e5O4c1dEx0cWYkNdSm5eYYgS5mcqYHOJFc9cjZjRTP99Rd5o8w9LVbVaBHVsZxjAtWZtt7cxGMjbzNtoWzOijZNyjpStYZYrYtB9VtFGjhNvqzVdppNHBk++jflxW-BX5Pz8FMTXzvlkVbN69dEk4XNopTjNE5zpjR9-zp9pTuAKFl9UskmyYFemYYi-Cyt8mD9Kt+FatZVYTZgAIew2RREUIbAZwuA5wOE4AX8AQwY-omEor4r+I-EdQeAk5-oOw600ge1zieApY6wQAA

**Comment by luigi-asprino** [comment]
Ok great! I didn't know this!
Thank you!
