### ISSUE TITLE
iter:XPath transforms XML to HTML before processing

### ISSUE THREAD

**Issue by jmkeil** [sparql-generate/sparql-generate#95]
There seems to be a problem with `iter:XPath` causing a transformation of the input XML to some HTML before processing. Example:
```
BASE <http://example.com/> 
PREFIX iter: <http://w3id.org/sparql-generate/iter/>

GENERATE { 
  <a> <b> ?source.
}
SOURCE <https://dblp.org/pid/76/11266.xml> AS ?source
WHERE {}
```
([execute](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZWQBxMgA5MgUiABVKYGkZCmoYSSoAI0kAfgdhOAxBAVkAX1kSAHkAVQUAYUpaegYHYzAMhAZrO2YGS2YAdgA2ZgBGEYAmQcH+di4ESVIKXPzCiFkAdQAJaISSkAAaEBluCDA0TC0IBzwAbQBdQ8hYRCRbDBgGGjwQA6OTsDeHxo11w90ewkEcC43iQDggSFuoAKWm+hiYrA43F4AhEYkxPD4MzmvwcSAwWhktm+VGyswQFAAbpgHFphDIALxSEAjfgABi5FG8IjAFNsnJAVViyncAA4udlxLIqDJhLoHIrkilqCrdNowOKALIjfoCsAwLDikb8kAULhspA0cW8kYCrAQFzi8a83lykCSWRawNBqhIYTiWLCJlUZihjVB+PUKAYUTiABSMBkWmjSZTAYTgdo7pFlPECggXApkAw0ZoRdFcfzWsywjAWHEABE2QByJAUKA2Ly96EUB1aBwUEwQCAAa28YAAhNGMi223mUtGdRAG+vN3rDSNfRQzRauVaBXaZA6neNXe6MJ7vb7-ZrG9RY7UaOSHNHY2vG1Qcy4UstEEads2TIC-3zQsYGLWxxCqBgzV0Gs6xLKCE2bVtxHWCAKBVEwKD4GAmQoPwKBZdglxXbdqGYTcNQ3VUrnEX5oRFPwsAYCBvg+XgQL8VkZGYOkQBKB4QFJDB3S4PBYAQOFDgQYRbD4JkEDwABWEogA)) as expected returns:
```
@base          <http://example.org/> .
@prefix iter:  <http://w3id.org/sparql-generate/iter/> .

<http://example.com/a>
        <http://example.com/b>  "<?xml version=\"1.0\"?> …
```

However, the following two queries
```
BASE <http://example.com/> 
PREFIX iter: <http://w3id.org/sparql-generate/iter/>

GENERATE { 
  <a> <b> ?source.
}
ITERATOR iter:XPath(<https://dblp.org/pid/76/11266.xml>, "/") AS ?source
WHERE {}
```
([execute](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZWQBxMgA5MgUiABVKYGkZCmoYSSoAI0kAfgdhOAxBAVkAX1lVeJjYgHkFbV0MXHU5PxoAClp6BgdjMAyEBms7ZgZLZgB2ADZmAEYZgCZJyf52LgRxABppEGYpEABKClIKXPzCiFkAdQAJaISSkA2QGW4IMDRMLQgHPABtAF0npBYIgkLYMDAGDQ8CBHs9XmBwZCaD9cACgcJBHAuN4kA4IEg-qACloYYYmKwONxeAIRGIqTw+Cs1nCHEgMFoZLYYVRsqsEBQAG6YBxaYQyAC8exm-AADHsKN4RGBObYpSAAKqxZTuAAce2y4lkVBkwl0DiNyRS1FNum0YHVAFkZuMFWAYFh1TN5SAKFxxUgaOrZTMFVgIC51fNZbL9SBJLJrUnk1QkMJxLFhMKqMw05bkwXqFAMKJxAApGAyLQ54ulxOFpO0CMqrniBQQLicyAYHM0Zuq-MN62ZYRgLDiAAi4oA5EgKFAbF45ziKIGtA4KCYIBAANbeMAAQhzGVH4-rKRztogg4vV-tTpmcYo7s90p9foDQb2svmYYjGCjGM4wTK0h2oPMAGEaA5Bwczzc8hyoWsuDbLRBB3GsSxQhCGybGAW1scQNQYd1dF7ftWxwwsRzHcRLggChTRMCg+BgYUKD8ChRXYY9TxvahmCvS1LzNb5xDhHEVT8LAGAgGFIV4NC-DFGRmH5EASkBEA2QwCMuDwWAEHxJ4EGEWw+GFBA8AAVhKIA)) and

```
BASE <http://example.com/> 
PREFIX iter: <http://w3id.org/sparql-generate/iter/>

GENERATE { 
  <a> <b> ?source.
}
SOURCE <https://dblp.org/pid/76/11266.xml> AS ?file
ITERATOR iter:XPath(?file, "/") AS ?source
WHERE {}
```
([execute](https://ci.mines-stetienne.fr/sparql-generate/playground.html#msg=N4IgJgpgZghgrgGwC4Ec4QE4E8QC4QBCAggMoCiABADwAWSSADrgPTMQAeMAtgwhAHQBjAPZdmAPgoAdAHYAFAEpkAYgEkAGhQCWSTLmp1GLZgHcAzFrD9hGAObMAzgxgYUCALS2IMzDF3MdTAlZWQBxMgA5MgUiABVKYGkZCmoYSSoAI0kAfgdhOAxBAVkAX1kSAHkAVQUAYUpaegYHYzAMhAZrO2YGS2YAdgA2ZgBGEYAmQcH+di4ESVIKbKgtPllVeJjYioVtXQxcdTk-GgAKZdWIABppEGYpEABKCkXc-MKIWQB1AAlohJKICuIBk3AgYDQmC0EAceAA2gBdYGQWCIJC2DAwBg0PAgIEgsFgDFYmiw3CI5HCQRwLjeJAOCBIeGgApaXGGJisDjcXgCERibk8PgzOb4hxIDBaGS2XFUbKzBAUABumAcWmEMgAvA8RvwAAwPCjeERgKW2bUgKqxZTuAAcD2y4lkVBkwl0DidyRS1Fdum0YAtAFkRv1DWAYFgLSMDSAKFwNUgaBa9SNDVgIC4LeM9Xr7SBJLJvUXi1QkMJxLFhCqqMwy57iw3qFAMKJxAApGAyLQ15utwuNou0DOm6XiBQQLhSyAYGs0Ydm+sD72ZYRgLDiAAiGoA5EgKFAbF497SKImtA4KCYIBAANbeMAAQhrGVX6-7KRrvogi4-X-9QZGPMKHDSMdRjOMEyTB49XGNMMwwLMczzAsvSXag61qGhJQcGs63fJcqF7Lgxy0QQbx7FtiPwgchxgEdbHEKoGHDXRZ3nUdqMbFc13EL4IAoV0TAoPgYBVCg-AoNV2GfV8f2oZgv09T83RhcR8VpU0-CwBgIFxLFeFIvx1RkZgFRAEokRAcUMAzLg8FgBAGWBBBhFsPgVQQPAAFYSiAA)) return:
```
@base          <http://example.org/> .
@prefix iter:  <http://w3id.org/sparql-generate/iter/> .

<http://example.com/a>
        <http://example.com/b>  "<html>\n\t\n\n<head>…
```

The problem also arises with other XML documents and using the offline JAR.

**Comment by maximelefrancois86** [comment]
Hi, 

sorry for the late, the issue should be solved in the next release.
